import { execFileSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { slugify } from '../../shared/slugify';

/**
 * Filesystem-only git introspection helpers. No simple-git dependency
 * and no shared state - each function is a pure predicate against the
 * local filesystem or a single shelled-out git command.
 *
 * Consumers: ipc handlers (tasks, projects, system, helpers), MCP
 * project context, and WorktreeManager.
 */

/** Check whether the project path is inside a git repository. */
export function isGitRepo(projectPath: string): boolean {
  return fs.existsSync(path.join(projectPath, '.git'));
}

/** Check whether the project path is a git worktree (has `.git` as a file, not a directory). */
export function isInsideWorktree(projectPath: string): boolean {
  const dotGit = path.join(projectPath, '.git');
  try {
    return fs.statSync(dotGit).isFile();
  } catch {
    return false;
  }
}

/**
 * Check whether the project path IS a Kangentic-managed worktree checkout.
 *
 * A preview project's path looks like `<parent>/.kangentic/worktrees/<slug>`.
 * We check that the immediate parent dir is `worktrees` and its parent is
 * `.kangentic`. This avoids false positives when the app itself runs from
 * inside a worktree (e.g. the CWD contains `.kangentic/worktrees/` early
 * in the path, but the project isn't itself a preview worktree).
 */
export function isKangenticWorktree(projectPath: string): boolean {
  // Normalize all separators to forward slashes so the check works on any OS
  const normalized = projectPath.replace(/\\/g, '/');
  const segments = normalized.split('/').filter(Boolean);
  if (segments.length < 3) return false;
  const parentSegment = segments[segments.length - 2];
  const grandparentSegment = segments[segments.length - 3];
  return parentSegment === 'worktrees' && grandparentSegment === '.kangentic';
}

/** Check whether a file is tracked by git (committed or staged). */
export function isFileTracked(projectPath: string, filePath: string): boolean {
  try {
    execFileSync('git', ['ls-files', '--error-unmatch', '--', filePath], {
      cwd: projectPath, stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check whether a branch name matches the auto-generated pattern for a task.
 * Auto-generated branches are `{slug}-{shortId}` where shortId is the first 8
 * chars of the task UUID. When the task was created off a non-default base
 * branch, the name is prefixed with the base as a namespace:
 * `{baseFlat}/{slug}-{shortId}`. The slug may have been truncated by the
 * dynamic path budget, so we check that the branch slug is a valid prefix of
 * the full slug. Custom branches set by the user will not match.
 */
export function isAutoGeneratedBranch(branchName: string, taskId: string, taskTitle: string): boolean {
  const shortId = taskId.slice(0, 8);
  const suffix = `-${shortId}`;
  if (!branchName.endsWith(suffix)) return false;

  const withoutSuffix = branchName.slice(0, -suffix.length);
  const firstSlashIndex = withoutSuffix.indexOf('/');
  const branchSlug = firstSlashIndex >= 0
    ? withoutSuffix.slice(firstSlashIndex + 1)
    : withoutSuffix;

  // Our auto-generated format has at most ONE slash (between the flattened
  // base-branch prefix and the task slug). User-supplied custom branches
  // with multiple segments (e.g. 'feature/bug/login') are rejected here.
  if (branchSlug.includes('/')) return false;

  if (branchSlug === 'task') return true; // fallback slug used when budget was 0
  const fullSlug = slugify(taskTitle) || 'task';
  return fullSlug.startsWith(branchSlug) && branchSlug.length > 0;
}
