/**
 * Turn a string into a filesystem-safe slug.
 * e.g. "Fix login bug (urgent!)" → "fix-login-bug-urgent"
 */
export function slugify(text: string, maxLen = 20): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/, '');
}

/**
 * Compose the auto-generated branch name, e.g. 'task-title-ab12cd34'.
 *
 * The base branch is deliberately not part of the name. It used to be, as a
 * folder for a non-default base ('develop/task-title-ab12cd34'), and that broke
 * every base without a '/' in its name: git stores a ref as a file, so no branch
 * can live in a folder named after another branch. Creation failed when the base
 * was checked out locally, and the push was rejected when it was only on the
 * remote. The base is recorded in the task row and in the worktree's
 * `kangentic.baseBranch` config, which is what everything reads.
 * `isAutoGeneratedBranch` still recognizes branches named the old way.
 */
export function computeAutoBranchName(slug: string, shortId: string): string {
  return `${slug}-${shortId}`;
}
