import * as fs from 'fs';
import * as path from 'path';
import { app, BrowserWindow, ipcMain } from 'electron';
import { autoUpdater } from 'electron-updater';
import { IPC } from '../shared/ipc-channels';
import { trackEvent, sanitizeErrorMessage } from './analytics/analytics';
import { normalizeReleaseNotes } from './updater-release-notes';

const CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000; // 4 hours
const INITIAL_DELAY_MS = 5000; // 5 seconds after launch
const RETRY_DELAY_MS = 30_000; // 30 seconds before retry

let checkTimeout: ReturnType<typeof setTimeout> | null = null;
let checkInterval: ReturnType<typeof setInterval> | null = null;
let updaterWindow: BrowserWindow | null = null;
let checkRetrying = false;
let downloadRetrying = false;

/**
 * Path to the auto-updater manifest, generated by electron-builder when
 * `--publish` is set. On packaged builds it lives in the platform's resources
 * directory. Exported for testing.
 * @internal
 */
export function manifestPath(): string {
  return path.join(process.resourcesPath, 'app-update.yml');
}

/**
 * True when the auto-updater manifest is present at its expected location.
 * Exported for testing.
 * @internal
 */
export function manifestExists(): boolean {
  return fs.existsSync(manifestPath());
}

/**
 * Returns true if the error is a known-transient download/network failure
 * that should not surface as `app_error` telemetry. Structural failures
 * (signature mismatch, bad manifest, disk full, permission denied, 4xx
 * client errors) still propagate so real bugs stay visible.
 */
export function isTransientUpdaterError(error: Error): boolean {
  const errorCode = (error as NodeJS.ErrnoException).code;
  const errorMessage = error.message ?? '';

  if (errorCode === 'ECONNRESET' || errorCode === 'ETIMEDOUT'
      || errorCode === 'EAI_AGAIN' || errorCode === 'ENOTFOUND'
      || errorCode === 'ENETUNREACH' || errorCode === 'EPIPE') {
    return true;
  }

  if (errorCode && /^HTTP_ERROR_(5\d\d|408|429|618)$/.test(errorCode)) {
    return true;
  }

  if (/net::ERR_/.test(errorMessage)) return true;
  if (/Request has been aborted by the server/i.test(errorMessage)) return true;
  if (/Cannot pipe ".*":/i.test(errorMessage)) return true;

  return false;
}

/** @internal Exported for testing. */
export async function checkWithRetry(): Promise<void> {
  try {
    await autoUpdater.checkForUpdates();
  } catch {
    console.log('[UPDATER] Check failed, retrying in 30s...');
    checkRetrying = true;
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
    try {
      await autoUpdater.checkForUpdates();
    } catch (retryError) {
      console.error('[UPDATER] Check failed after retry:', retryError);
    } finally {
      checkRetrying = false;
    }
  }
}

/** @internal Exported for testing. */
export async function downloadWithRetry(): Promise<void> {
  try {
    await autoUpdater.downloadUpdate();
  } catch (firstError) {
    console.log('[UPDATER] Download failed, retrying in 30s:', firstError);
    downloadRetrying = true;
    try {
      await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
      await autoUpdater.downloadUpdate();
    } catch (retryError) {
      console.error('[UPDATER] Download failed after retry:', retryError);
    } finally {
      downloadRetrying = false;
    }
  }
}

/**
 * Registered on every path that bails out of updater init (dev, Linux, and a
 * build with no update manifest). The renderer's updater surfaces still exist
 * on those paths, so without these `ipcRenderer.invoke` rejects with
 * `No handler registered` and surfaces as an unhandled rejection.
 */
function registerNoOpUpdaterHandlers(): void {
  ipcMain.handle(IPC.UPDATE_CHECK, () => {});
  ipcMain.handle(IPC.UPDATE_INSTALL, () => {});
}

/**
 * Initialize the auto-updater for packaged builds (Windows and macOS only).
 * Linux users update via the launcher package (`npx kangentic`).
 */
export function initUpdater(mainWindow: BrowserWindow): void {
  if (!app.isPackaged || process.platform === 'linux') {
    // The renderer's release-notes modal reaches `installUpdate()` from its
    // primary button, and the Developer tab can open that modal with fixture
    // notes in dev. Register no-ops so the invoke resolves instead of
    // rejecting with `No handler registered` (an unhandled rejection).
    registerNoOpUpdaterHandlers();
    return;
  }

  updaterWindow = mainWindow;

  // electron-builder generates app-update.yml only when `--publish` is set,
  // so a misbuilt release (or a locally-packaged DMG/EXE without --publish)
  // can ship without it. Without this guard, electron-updater raises
  // ENOENT on every scheduled check and pollutes telemetry. Register
  // no-op IPC handlers so the renderer's "check for updates" UI does not
  // throw `No handler registered`, fire one telemetry event so we can
  // catch a recurrence in production, and bail before scheduling.
  if (!manifestExists()) {
    console.warn(`[UPDATER] Skipping init: ${manifestPath()} not found.`);
    registerNoOpUpdaterHandlers();
    trackEvent('app_error', {
      source: 'updater',
      message: 'missing_manifest',
    });
    return;
  }

  // We control the download -- don't auto-download on check
  autoUpdater.autoDownload = false;
  // Install pending updates silently when the user quits normally
  autoUpdater.autoInstallOnAppQuit = true;

  // macOS differential download reads a cached update.zip from
  // ~/Library/Caches/<appId>-updater/pending/, which macOS evicts under
  // disk pressure. That race produces a bare `ENOENT: no such file or
  // directory, open '<path>'` error, historically our dominant updater
  // failure. Full redownload is an acceptable tradeoff for eliminating
  // the flakiness. See MacUpdater.js:88-103 for the cached-zip read
  // path we are bypassing.
  if (process.platform === 'darwin') {
    autoUpdater.disableDifferentialDownload = true;
  }

  // IPC handlers for renderer
  ipcMain.handle(IPC.UPDATE_CHECK, () => checkWithRetry());

  ipcMain.handle(IPC.UPDATE_INSTALL, () => {
    autoUpdater.quitAndInstall(true, true);
  });

  // When an update is available, start downloading immediately (with retry).
  autoUpdater.on('update-available', () => {
    console.log('[UPDATER] Update available, downloading...');
    void downloadWithRetry();
  });

  // When download completes, notify the renderer
  autoUpdater.on('update-downloaded', (info) => {
    console.log('[UPDATER] Update downloaded:', info.version);
    if (updaterWindow && !updaterWindow.isDestroyed()) {
      updaterWindow.webContents.send(IPC.UPDATE_DOWNLOADED, {
        version: info.version,
        releaseNotes: normalizeReleaseNotes(info.releaseNotes),
      });
    }
  });

  // Log errors but never surface to user. Skip analytics during retry to
  // avoid double-counting transient failures that resolve on second attempt.
  // Also filter known-transient failure classes so network blips and presigned
  // URL expiries do not pollute the app_error signal.
  autoUpdater.on('error', (error) => {
    console.error('[UPDATER] Error:', error);
    if (checkRetrying || downloadRetrying) return;
    if (isTransientUpdaterError(error)) {
      const errorCode = (error as NodeJS.ErrnoException).code;
      console.log('[UPDATER] Suppressing transient error telemetry:',
        errorCode ?? error.message.slice(0, 80));
      return;
    }
    trackEvent('app_error', {
      source: 'updater',
      message: sanitizeErrorMessage(error.message),
    });
  });

  // Schedule checks
  checkTimeout = setTimeout(() => {
    console.log('[UPDATER] Checking for updates...');
    checkWithRetry();

    checkInterval = setInterval(() => {
      console.log('[UPDATER] Checking for updates...');
      checkWithRetry();
    }, CHECK_INTERVAL_MS);
  }, INITIAL_DELAY_MS);
}

/**
 * Update the window reference used by the auto-updater. Called when macOS
 * recreates the window after all windows were closed (dock icon click).
 */
export function updateUpdaterWindow(mainWindow: BrowserWindow): void {
  updaterWindow = mainWindow;
}

/**
 * Synchronously clear updater timers. Called from syncShutdownCleanup().
 */
export function stopUpdaterTimers(): void {
  if (checkTimeout) {
    clearTimeout(checkTimeout);
    checkTimeout = null;
  }
  if (checkInterval) {
    clearInterval(checkInterval);
    checkInterval = null;
  }
}
