import simpleGit from 'simple-git';
import { TaskRepository } from '../../db/repositories/task-repository';
import { WorktreeManager, isGitRepo, isAutoGeneratedBranch } from '../../git/worktree-manager';
import type { Task } from '../../../shared/types';
import type { IpcContext } from '../ipc-context';

/**
 * Create a worktree for a task if needed and update the DB + task object in place.
 * No-ops when worktrees are disabled or project isn't a git repo.
 * Throws on worktree creation failure (e.g. duplicate branch).
 */
export async function ensureTaskWorktree(context: IpcContext, task: Task, tasks: TaskRepository, projectPath?: string | null, options?: { signal?: AbortSignal }): Promise<void> {
  options?.signal?.throwIfAborted();
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;
  if (!resolvedProjectPath) return;
  const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
  const worktreeManager = new WorktreeManager(resolvedProjectPath);
  const result = await worktreeManager.withLock(() => worktreeManager.ensureWorktree(task, config.git));
  if (result) {
    tasks.update({ id: task.id, worktree_path: result.worktreePath, branch_name: result.branchName });
    Object.assign(task, tasks.getById(task.id));
  }
}

/**
 * Checkout the task's branch in the main repo for non-worktree tasks.
 *
 * Custom branch names (not matching the auto-generated pattern) are fetched
 * from origin, created from base_branch or remote if needed, then checked out.
 * Auto-generated branches fall through to the base_branch checkout path.
 *
 * No-ops when: no project path, task uses a worktree, not a git repo,
 * or task has neither a custom branch_name nor a base_branch.
 * Throws on dirty repo or checkout failure so the caller can block agent spawn.
 */
export async function ensureTaskBranchCheckout(
  task: Task,
  projectPath?: string | null,
  options?: { signal?: AbortSignal },
): Promise<void> {
  options?.signal?.throwIfAborted();
  if (!projectPath) return;
  if (task.worktree_path) return;
  if (!isGitRepo(projectPath)) return;

  // Custom branch name: fetch latest, create if needed, then checkout
  if (task.branch_name && !isAutoGeneratedBranch(task.branch_name, task.id, task.title)) {
    await WorktreeManager.withGitLock(projectPath, async () => {
      const git = simpleGit(projectPath);

      // Always fetch latest from origin (best-effort, fails silently if offline)
      try {
        await git.raw(['fetch', 'origin', task.branch_name!]);
      } catch {
        // Offline, no remote, or branch not on remote
      }

      // Check if branch exists locally (user's local may be ahead of remote, that's fine)
      let branchExists = false;
      try {
        await git.raw(['rev-parse', '--verify', task.branch_name!]);
        branchExists = true;
      } catch {
        // Branch does not exist locally
      }

      if (!branchExists) {
        // Check if it exists on remote (we already fetched above)
        let existsOnRemote = false;
        try {
          await git.raw(['rev-parse', '--verify', `origin/${task.branch_name}`]);
          existsOnRemote = true;
        } catch {
          // Not on remote either
        }

        if (existsOnRemote) {
          // Create local branch tracking the remote
          await git.raw(['branch', task.branch_name!, `origin/${task.branch_name}`]);
        } else {
          // Branch doesn't exist anywhere. Create from base_branch.
          const baseBranch = task.base_branch || 'main';
          await git.raw(['branch', task.branch_name!, baseBranch]);
        }
      }

      const worktreeManager = new WorktreeManager(projectPath);
      await worktreeManager.checkoutBranch(task.branch_name!);
    });
    return;
  }

  // Fall through to existing base_branch checkout logic
  if (!task.base_branch) return;

  const worktreeManager = new WorktreeManager(projectPath);
  await worktreeManager.withLock(() => worktreeManager.checkoutBranch(task.base_branch!));
}
