import path from 'node:path';
import simpleGit from 'simple-git';
import { IPC } from '../../../shared/ipc-channels';
import { TaskRepository } from '../../db/repositories/task-repository';
import { WorktreeManager, type GitWaitProgress } from '../../git/worktree-manager';
import { prepareWorktreeFolder } from '../../git/task-worktree-folder';
import { isGitRepo, isAutoGeneratedBranch, hasCommits } from '../../git/git-checks';
import { fetchIfStale } from '../../git/fetch-throttle';
import { isShuttingDown } from '../../shutdown-state';
import { DEFAULT_AGENT, type Task } from '../../../shared/types';
import { getProjectRepos } from './project-repos';
import { applyProfileToLane } from '../../transition-engine/column-strategy';
import { loadTaskProfile } from './task-profile';
import type { IpcContext } from '../ipc-context';

/**
 * Resolution of the agent that will run this task, for the worktree-skip
 * check. This MUST mirror `resolveTargetAgent`'s chain (task override ->
 * COLUMN PROFILE's rung for this column -> column override -> project default
 * -> global fallback), because skipping the worktree commits us to remote
 * execution: if this function and the spawn-time resolution disagree, a LOCAL
 * agent spawns with `cwd = projectPath` (transition-engine's
 * `task.worktree_path || projectPath` fallback) and runs unisolated in the
 * user's main checkout.
 *
 * The profile tier is why this is not just "read the lane": a task riding a
 * profile that re-points this column at a remote-execution agent must skip the
 * worktree here, exactly as the spawn will.
 *
 * The column layer is read from the task's CURRENT swimlane, which is the
 * destination lane at every call site (the move/create/promote/unarchive
 * flows all commit the row to the destination before the worktree phase).
 */
function resolveWorktreeCheckAgentName(task: Task, context: IpcContext, projectPath: string): string {
  if (task.agent_override) return task.agent_override;
  const project = context.projectRepo.list().find((candidate) => candidate.path === projectPath);
  if (project?.id && task.swimlane_id) {
    const { swimlanes } = getProjectRepos(context, project.id);
    const lane = applyProfileToLane(
      swimlanes.getById(task.swimlane_id),
      loadTaskProfile(context, task, projectPath),
    );
    if (lane?.agent_override) return lane.agent_override;
  }
  return project?.default_agent ?? DEFAULT_AGENT;
}

/**
 * Thrown when a branch checkout would change the working tree under another
 * task's live agent. Typed so the callers that deliberately do not fail the
 * whole operation (create, unarchive, promote) can still tell the user why no
 * agent started, instead of logging to a console nobody is reading.
 */
export class BranchCheckoutBlockedError extends Error {
  constructor(
    readonly directory: string,
    readonly blockingTaskId: string,
    readonly blockingTaskTitle: string | null,
    readonly blockerKind: 'task' | 'command-terminal' = 'task',
  ) {
    const blocker = blockerKind === 'command-terminal'
      ? 'a Command Terminal'
      : (blockingTaskTitle ? `"${blockingTaskTitle}"` : `task ${blockingTaskId.slice(0, 8)}`);
    const remedy = blockerKind === 'command-terminal'
      ? 'Close that terminal, or enable worktree mode so each task gets its own checkout.'
      : 'Stop that task, or enable worktree mode so each task gets its own checkout.';
    super(`Cannot switch branches in ${directory}: ${blocker} is already running an agent there. ${remedy}`);
    this.name = 'BranchCheckoutBlockedError';
  }
}

/** True when two paths denote the same directory, comparing the way the platform does. */
function isSameDirectory(first: string, second: string): boolean {
  try {
    return path.relative(path.resolve(first), path.resolve(second)) === '';
  } catch {
    return false;
  }
}

/**
 * Refuse to touch a working directory that another task's agent is live in.
 *
 * Keyed on `Session.cwd`, not on `task.worktree_path`: the cwd is where the
 * agent actually is, whereas re-reading the task row is an indirection that can
 * disagree with reality. Queued sessions count, because the session manager
 * stamps `cwd` on the queued placeholder before the PTY exists.
 *
 * A Command Terminal counts too, deliberately. It spawns a real agent with
 * `cwd = projectRoot` (`handlers/transient-sessions.ts`), so checking out under
 * it changes files under a live agent exactly as a task would. The previous
 * guard missed this because it resolved each session's `taskId` to a task row
 * and a transient id resolves to nothing, so it silently skipped them.
 */
function assertNoOtherAgentInDirectory(
  context: IpcContext,
  taskId: string,
  directory: string,
): void {
  const occupant = context.sessionManager.listSessions().find((session) =>
    session.taskId !== taskId
    && (session.status === 'running' || session.status === 'queued')
    && Boolean(session.cwd)
    && isSameDirectory(session.cwd, directory));
  if (!occupant) return;

  if (occupant.transient) {
    throw new BranchCheckoutBlockedError(directory, occupant.taskId, null, 'command-terminal');
  }

  let blockingTitle: string | null = null;
  try {
    blockingTitle = getProjectRepos(context).tasks.getById(occupant.taskId)?.title ?? null;
  } catch {
    // Naming the blocker is a nicety; never let it turn into the failure.
  }
  throw new BranchCheckoutBlockedError(directory, occupant.taskId, blockingTitle);
}

/** The git step that failed before a born-into-a-column task could spawn. */
export type SpawnFailureStep = 'worktree' | 'checkout';

/**
 * Deliberately the same wording the drag path already toasts
 * (`Worktree setup failed: ...` in handlers/task-move.ts), so the same
 * underlying git failure reads identically whether the task was dragged in or
 * born into the column.
 */
const SPAWN_FAILURE_STEP_LABEL: Record<SpawnFailureStep, string> = {
  worktree: 'Worktree setup failed',
  checkout: 'Branch checkout failed',
};

/**
 * Shorten to at most `limit` characters, preferring to end on a complete
 * SENTENCE and falling back to a word boundary.
 *
 * A blind slice mangles the two shapes git errors actually take here.
 * `describeUnresolvableBase` ends in a branch LIST, so the cut lands inside it:
 * a hard slice half-prints a branch name (reads as a corrupt name), and a
 * word-boundary cut leaves the dangling label "Branches found:..." which
 * promises a list and then shows nothing. Ending at the previous sentence drops
 * the list cleanly and keeps the remediation sentence whole, which is the part
 * the user acts on. An opaque one-sentence error has no period to fall back to,
 * so that keeps the word-boundary cut plus an ellipsis.
 */
function shortenForNotice(text: string, limit: number): string {
  if (text.length <= limit) return text;
  const hardCut = text.slice(0, limit);

  // A sentence end late enough to still carry the substance.
  const lastSentenceEnd = Math.max(hardCut.lastIndexOf('. '), hardCut.lastIndexOf('? '), hardCut.lastIndexOf('! '));
  if (lastSentenceEnd > limit * 0.5) return hardCut.slice(0, lastSentenceEnd + 1);

  const lastSpace = hardCut.lastIndexOf(' ');
  const cut = lastSpace > limit * 0.6 ? hardCut.slice(0, lastSpace) : hardCut;
  return `${cut.trimEnd()}...`;
}

/**
 * User-facing summary of why a spawn did not happen.
 *
 * `BranchCheckoutBlockedError` keeps its own message verbatim - it is written
 * for a user and names both the blocker and the remedy. Anything else is the
 * step that failed plus the error's FIRST line, capped: raw git errors run to
 * several lines and would swamp a toast.
 *
 * The step label is dropped when the error already opens by naming that step
 * (`describeUnresolvableBase` starts "Cannot create worktree: ..."), which would
 * otherwise read "Worktree setup failed: Cannot create worktree: ...". Prefixing
 * is for the OPAQUE errors - a bare `EBUSY` or `fatal: ...` says nothing about
 * which step produced it.
 */
function describeSpawnFailure(step: SpawnFailureStep, error: unknown): string {
  if (error instanceof BranchCheckoutBlockedError) return error.message;

  const maxDetailLength = 200;
  const rawMessage = error instanceof Error ? error.message : String(error);
  const firstLine = (rawMessage.split('\n')[0] ?? '').trim();
  if (!firstLine) return `${SPAWN_FAILURE_STEP_LABEL[step]}.`;
  const detail = shortenForNotice(firstLine, maxDetailLength);
  if (/^cannot (create|check ?out)\b/i.test(detail)) return detail;
  return `${SPAWN_FAILURE_STEP_LABEL[step]}: ${detail}`;
}

/**
 * Tell the user their task was created but its agent did not start.
 *
 * The create / promote / unarchive / MCP-auto-spawn paths deliberately do not
 * fail the whole operation when a git step fails: the task really was created.
 * But "created and silently not spawned" is indistinguishable from "created and
 * spawned", so a console line is not good enough.
 *
 * Every worktree and checkout failure notifies, not only the actionable ones.
 * This used to narrow to `BranchCheckoutBlockedError`, reasoning that an
 * arbitrary git failure has no user-actionable message. What that actually did
 * was leave the WORKTREE stage silent at all five call sites - which is how
 * task #538 left a healthy-looking card (null session, null worktree) after
 * `git worktree add` refused a branch already checked out elsewhere. A vague
 * notice beats a card that lies, and raw git text reaching a user is already
 * precedent: the drag path's toast says `Worktree setup failed: <raw git error>`.
 *
 * Scope is those two git steps. A failure in the SPAWN step after them still
 * only logs (see `spawnAgent`), so that case keeps the #538 symptom.
 *
 * A task MOVE deliberately does not call this - it rejects the in-flight invoke
 * instead, which the renderer already toasts (see handlers/task-move.ts).
 */
export function notifySpawnBlocked(
  context: IpcContext,
  task: Task,
  step: SpawnFailureStep,
  error: unknown,
  projectId?: string | null,
): void {
  // A quit that closes the DB or kills git mid-step surfaces here as an ordinary
  // failure. While this only forwarded `BranchCheckoutBlockedError` that could
  // never happen; now that every error notifies, shutdown artifacts would toast
  // on the way out ("Worktree setup failed: The database connection is not
  // open"). `handleTaskMove` already bails this way on its own failure paths,
  // and the window is not reliably destroyed before the DB closes.
  if (isShuttingDown()) return;
  if (!context.mainWindow || context.mainWindow.isDestroyed()) return;
  context.mainWindow.webContents.send(
    IPC.TASK_SPAWN_BLOCKED,
    task.id,
    task.title,
    describeSpawnFailure(step, error),
    projectId ?? context.currentProjectId ?? undefined,
  );
}

/**
 * Create a worktree for a task if needed and update the DB + task object in place.
 * No-ops when worktrees are disabled, the project isn't a git repo, the repo has no commits yet
 * (unborn HEAD), or the resolved agent's execution mode for this project is 'remote' (the agent
 * runs against a server-side directory instead - see `agent.execution` in AppConfig and
 * `ResolvedExecutionTarget`; `task.worktree_path` stays null so `cwd` falls back to the project
 * path, per transition-engine.ts).
 * Throws on worktree creation failure (e.g. duplicate branch, or an unresolvable base branch).
 */
export async function ensureTaskWorktree(
  context: IpcContext,
  task: Task,
  tasks: TaskRepository,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void },
): Promise<void> {
  options?.signal?.throwIfAborted();
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;
  if (!resolvedProjectPath) return;
  const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
  const agentName = resolveWorktreeCheckAgentName(task, context, resolvedProjectPath);
  if (config.agent.execution[agentName]?.mode === 'remote') return;
  // No-commits and base-branch-resolution guards live inside
  // WorktreeManager.ensureWorktree (via resolveWorktreeBase) so every caller - this one, the
  // create_worktree transition action, MCP auto-spawn - gets identical behavior.
  // A task that predates the numeric folder scheme and has already been through
  // Done has no worktree_path left to remember where it lived. Recover that from
  // its session history BEFORE creating, so it returns to its original path
  // instead of being relocated. See TaskRepository.recoverLegacyWorktreeFolder.
  prepareWorktreeFolder(task, tasks, resolvedProjectPath);
  const worktreeManager = new WorktreeManager(resolvedProjectPath);
  const result = await worktreeManager.withLock(
    () => worktreeManager.ensureWorktree(task, config.git, { onProgress: options?.onProgress, signal: options?.signal }),
    { label: `create-worktree:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress },
  );
  if (result) {
    tasks.recordWorktree(task.id, result.worktreePath, result.branchName, result.worktreeFolder);
    Object.assign(task, tasks.getById(task.id));
  }
}

/**
 * Checkout the task's branch in the main repo for non-worktree tasks.
 *
 * Custom branch names (not matching the auto-generated pattern) are fetched
 * from origin, created from base_branch or remote if needed, then checked out.
 * Auto-generated branches fall through to the base_branch checkout path.
 *
 * No-ops when: no project path, task uses a worktree, not a git repo,
 * or task has neither a custom branch_name nor a base_branch.
 * Throws on dirty repo or checkout failure so the caller can block agent spawn.
 *
 * Also throws `BranchCheckoutBlockedError` when another task already has a live
 * agent in the directory about to be checked out. That check lives HERE, beside
 * the checkout it protects, rather than in a caller: it used to sit in
 * `task-move.ts` keyed on `task.base_branch`, while the decision to check out is
 * keyed on `usesCustomBranch || base_branch`. A task with a custom branch and no
 * base branch therefore checked out with the guard never running, changing the
 * working tree under someone else's agent. Co-locating them makes that class of
 * drift impossible.
 */
export async function ensureTaskBranchCheckout(
  context: IpcContext,
  task: Task,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void },
): Promise<void> {
  options?.signal?.throwIfAborted();
  if (!projectPath) return;
  if (task.worktree_path) return;
  if (!isGitRepo(projectPath)) return;

  const usesCustomBranch = Boolean(
    task.branch_name && !isAutoGeneratedBranch(task.branch_name, task.id, task.title),
  );
  // Nothing to check out either way, so stop before touching git at all.
  if (!usesCustomBranch && !task.base_branch) return;
  // Same unborn-HEAD case WorktreeManager.ensureWorktree guards for the worktree path: with no
  // commits there is no branch to fetch, create, or check out, and every git call below would
  // fail on the ref. Deliberately AFTER the cheap guards - it shells out, and the common move
  // has no branch work to do.
  if (!(await hasCommits(projectPath))) return;

  // Custom branch name: fetch latest, create if needed, then checkout
  if (usesCustomBranch) {
    await WorktreeManager.withGitLock(projectPath, async () => {
      // Inside the per-project git queue, so the probe and the checkout are
      // atomic against every other checkout on this project. That is why no new
      // directory-scoped lock is needed: a third lock ordering alongside
      // withTaskLock (per-task, deliberately parallel across tasks) and
      // projectQueues would be a deadlock surface.
      assertNoOtherAgentInDirectory(context, task.id, projectPath);
      const git = simpleGit(projectPath);

      // Emit 'fetching' once the job actually starts (after any queue wait) so
      // the card flips from the "Waiting..." label to "Fetching latest...".
      options?.onProgress?.('fetching');
      // Fetch latest from origin (throttled to avoid redundant network I/O)
      await fetchIfStale(git, projectPath, task.branch_name!, { signal: options?.signal });
      options?.onProgress?.('switching-branch');
      options?.signal?.throwIfAborted();

      // Check if branch exists locally (user's local may be ahead of remote, that's fine)
      let branchExists = false;
      try {
        await git.raw(['rev-parse', '--verify', task.branch_name!]);
        branchExists = true;
      } catch {
        // Branch does not exist locally
      }

      if (!branchExists) {
        // Check if it exists on remote (we already fetched above)
        let existsOnRemote = false;
        try {
          await git.raw(['rev-parse', '--verify', `origin/${task.branch_name}`]);
          existsOnRemote = true;
        } catch {
          // Not on remote either
        }

        if (existsOnRemote) {
          // Create local branch tracking the remote
          await git.raw(['branch', task.branch_name!, `origin/${task.branch_name}`]);
        } else {
          // Branch doesn't exist anywhere. Create from base_branch.
          const baseBranch = task.base_branch || 'main';
          await git.raw(['branch', task.branch_name!, baseBranch]);
        }
      }

      const worktreeManager = new WorktreeManager(projectPath);
      await worktreeManager.checkoutBranch(task.branch_name!);
    }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
    return;
  }

  // Fall through to existing base_branch checkout logic. `usesCustomBranch` being false
  // already guarantees a base_branch above; this narrows it for TypeScript.
  if (!task.base_branch) return;

  const worktreeManager = new WorktreeManager(projectPath);
  await worktreeManager.withLock(async () => {
    assertNoOtherAgentInDirectory(context, task.id, projectPath);
    // Once the job actually starts (after any queue wait), flip the card from
    // the "Waiting..." label to an active label for the duration of the checkout.
    options?.onProgress?.('switching-branch');
    await worktreeManager.checkoutBranch(task.base_branch!);
  }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
}
