/**
 * Unit tests for auto-generated worktree branch naming.
 *
 * The name is `{slug}-{shortId}` whatever the base branch. Branches from before
 * the base was dropped from the name carry it as one folder
 * (`{baseFlat}/{slug}-{shortId}`), and `isAutoGeneratedBranch` must keep
 * recognizing them so a title edit and a cleanup still treat them as Kangentic's.
 */
import { describe, it, expect } from 'vitest';
import { computeAutoBranchName } from '../../src/shared/slugify';
import { isAutoGeneratedBranch } from '../../src/main/git/git-checks';

describe('computeAutoBranchName', () => {
  it('joins the slug and the short id', () => {
    expect(computeAutoBranchName('task-title', 'ab12cd34')).toBe('task-title-ab12cd34');
  });
});

describe('isAutoGeneratedBranch -- current and older base-folder names', () => {
  const taskId = 'ab12cd34-5678-90ab-cdef-111122223333';
  const title = 'Fix login bug';

  it('matches the current name', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches the fallback "task" slug', () => {
    expect(isAutoGeneratedBranch('task-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches an older name with its base as a folder', () => {
    expect(isAutoGeneratedBranch('staging/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches an older name whose base had slashes (flattened)', () => {
    expect(isAutoGeneratedBranch('bugfix-inacc-adjustments/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches an older name whose base contains dots (e.g. release/v2.0)', () => {
    // Flattened base 'release-v2.0' contains '.' - must still be recognized
    // so title-edit rename works on tasks cut from version-tagged base branches.
    expect(isAutoGeneratedBranch('release-v2.0/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches an older name whose base contains underscores', () => {
    expect(isAutoGeneratedBranch('feature_x/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches truncated slugs (dynamic MAX_PATH budget)', () => {
    expect(isAutoGeneratedBranch('fix-login-ab12cd34', taskId, title)).toBe(true);
    expect(isAutoGeneratedBranch('staging/fix-login-ab12cd34', taskId, title)).toBe(true);
  });

  it('does not match user-supplied custom branches that look nothing like the slug', () => {
    expect(isAutoGeneratedBranch('feature/something-else-ab12cd34', taskId, title)).toBe(false);
  });

  it('does not match branches with the wrong shortId suffix', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-99999999', taskId, title)).toBe(false);
  });

  it('does not match branches whose prefix contains invalid characters (e.g. user custom with slashes)', () => {
    // 'feature/sub.path' has a '.' which isn't in our flattened-base charset,
    // so we treat it as a user custom name and refuse to rename.
    expect(isAutoGeneratedBranch('feature/sub.path/fix-login-bug-ab12cd34', taskId, title)).toBe(false);
  });
});
