/**
 * `notifySpawnWarning` sends `task:spawnWarning` for a spawn that PROCEEDED
 * from a possibly-stale base (network/credential fetch failure). Unlike
 * `notifySpawnBlocked` the agent did start, so the renderer toasts the message
 * verbatim with no "did not start its agent" framing.
 *
 * The load-bearing contract pinned here is the COOLDOWN: one toast per
 * project per reason class per minute. Every affected card carries its own
 * sticky spawn-progress note, so the toast is only the attention-getter - a
 * bulk unarchive of N tasks while offline must produce ONE toast, not N.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {},
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isGitRepo: vi.fn(() => true),
  hasCommits: vi.fn(async () => true),
  isAutoGeneratedBranch: vi.fn(() => false),
  isInsideWorktree: vi.fn(() => true),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({ fetchIfStale: vi.fn(async () => 'main') }));

vi.mock('simple-git', () => ({
  default: () => ({ raw: vi.fn(async () => '') }),
}));

vi.mock('../../src/main/shutdown-state', () => ({
  isShuttingDown: vi.fn(() => false),
  setShuttingDown: vi.fn(),
}));

import {
  notifySpawnWarning,
  __resetSpawnWarningCooldownsForTest,
} from '../../src/main/ipc/helpers/task-git';
import { isShuttingDown } from '../../src/main/shutdown-state';
import { IPC } from '../../src/shared/ipc-channels';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task } from '../../src/shared/types';

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'aaaa1111-0000-0000-0000-000000000000',
    display_id: 1,
    title: 'A task',
    ...overrides,
  } as Task;
}

function makeContext(send: (...args: unknown[]) => void): IpcContext {
  return {
    mainWindow: { isDestroyed: () => false, webContents: { send } },
    currentProjectId: 'ambient-project',
  } as unknown as IpcContext;
}

const MESSAGE = "\"A task\": could not fetch latest 'main' from origin (network unreachable). Starting from the last fetched state.";

describe('notifySpawnWarning', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    __resetSpawnWarningCooldownsForTest();
  });

  it('sends taskId, the verbatim message, and the EXPLICIT projectId', () => {
    const send = vi.fn();
    const task = makeTask();

    notifySpawnWarning(makeContext(send), task, MESSAGE, 'explicit-project', 'network');

    expect(send).toHaveBeenCalledExactlyOnceWith(
      IPC.TASK_SPAWN_WARNING,
      task.id,
      MESSAGE,
      'explicit-project',
    );
  });

  it('falls back to context.currentProjectId when no explicit projectId is passed', () => {
    const send = vi.fn();
    const task = makeTask();

    notifySpawnWarning(makeContext(send), task, MESSAGE, null, 'network');

    expect(send).toHaveBeenCalledWith(IPC.TASK_SPAWN_WARNING, task.id, MESSAGE, 'ambient-project');
  });

  it('suppresses a second warning for the same project and reason within the cooldown', () => {
    const send = vi.fn();
    const context = makeContext(send);

    notifySpawnWarning(context, makeTask({ id: 'task-a' }), MESSAGE, 'explicit-project', 'network');
    notifySpawnWarning(context, makeTask({ id: 'task-b' }), MESSAGE, 'explicit-project', 'network');

    // This IS the bulk-unarchive-while-offline scenario: N tasks, one toast.
    expect(send).toHaveBeenCalledTimes(1);
  });

  it('a different reason class for the same project is not suppressed', () => {
    const send = vi.fn();
    const context = makeContext(send);

    notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'network');
    notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'auth');

    expect(send).toHaveBeenCalledTimes(2);
  });

  it('a different project with the same reason is not suppressed', () => {
    const send = vi.fn();
    const context = makeContext(send);

    notifySpawnWarning(context, makeTask(), MESSAGE, 'project-one', 'network');
    notifySpawnWarning(context, makeTask(), MESSAGE, 'project-two', 'network');

    expect(send).toHaveBeenCalledTimes(2);
  });

  it('sends again once the cooldown window has elapsed', () => {
    const nowSpy = vi.spyOn(Date, 'now');
    const send = vi.fn();
    const context = makeContext(send);

    nowSpy.mockReturnValue(0);
    notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'network');

    nowSpy.mockReturnValue(59_999);
    notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'network');
    expect(send).toHaveBeenCalledTimes(1);

    nowSpy.mockReturnValue(60_001);
    notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'network');
    expect(send).toHaveBeenCalledTimes(2);
  });

  it('sends nothing while the app is shutting down', () => {
    const send = vi.fn();
    vi.mocked(isShuttingDown).mockReturnValueOnce(true);

    notifySpawnWarning(makeContext(send), makeTask(), MESSAGE, 'explicit-project', 'network');

    expect(send).not.toHaveBeenCalled();
  });

  it('sends nothing when context.mainWindow is null, without throwing', () => {
    const context = {
      mainWindow: null,
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;

    expect(() => notifySpawnWarning(context, makeTask(), MESSAGE, 'explicit-project', 'network')).not.toThrow();
  });

  it('sends nothing when the window is destroyed, and does NOT consume the cooldown', () => {
    const send = vi.fn();
    const destroyedContext = {
      mainWindow: { isDestroyed: () => true, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;

    notifySpawnWarning(destroyedContext, makeTask(), MESSAGE, 'explicit-project', 'network');
    expect(send).not.toHaveBeenCalled();

    // A suppressed-by-guard call must not burn the cooldown slot: the next
    // live-window warning still reaches the user.
    notifySpawnWarning(makeContext(send), makeTask(), MESSAGE, 'explicit-project', 'network');
    expect(send).toHaveBeenCalledTimes(1);
  });
});
