/**
 * `notifySpawnBlocked` sends `task:spawnBlocked` for EVERY worktree/checkout
 * failure, and stamps it with an EXPLICIT `projectId` whenever the caller
 * supplies one - never falling back to the ambient `context.currentProjectId` in
 * that case. The MCP auto-spawn path (`agent-spawn.ts`) depends on that: it
 * targets whichever project the tool named, which is often not the focused
 * project, so `projectId ?? context.currentProjectId` must resolve to the
 * EXPLICIT id when both are present. Every other call site stubs this function
 * as a bare `vi.fn()` and never inspects its arguments, so this file is the only
 * place the `??` order (and the two early-return guards) is pinned.
 *
 * The "every failure" half is new, and is the fix for task #538. This used to be
 * `notifyBranchCheckoutBlocked`, which returned early for anything that was not
 * a `BranchCheckoutBlockedError` on the reasoning that an arbitrary git failure
 * has no user-actionable message. What that actually did was leave the WORKTREE
 * stage silent at all five born-into-a-column call sites: `git worktree add`
 * refused a branch already checked out elsewhere, and the card sat there with a
 * null session and a null worktree looking exactly like a healthy one.
 *
 * Red-green: the "notifies for an arbitrary git failure" tests below are the
 * inversion of the old narrowing test, and red against the pre-fix helper.
 */

import { describe, it, expect, vi } from 'vitest';

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {},
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isGitRepo: vi.fn(() => true),
  hasCommits: vi.fn(async () => true),
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({ fetchIfStale: vi.fn(async () => 'main') }));

vi.mock('simple-git', () => ({
  default: () => ({ raw: vi.fn(async () => '') }),
}));

vi.mock('../../src/main/shutdown-state', () => ({
  isShuttingDown: vi.fn(() => false),
  // Not exercised by this file, but declared so an unrelated import reaching
  // for it (task-git.ts pulls in project-repos, column-strategy,
  // task-profile, TaskRepository) fails as a real assertion instead of a
  // confusing "undefined is not a function" in a file this suite never touches.
  setShuttingDown: vi.fn(),
}));

import { notifySpawnBlocked, BranchCheckoutBlockedError } from '../../src/main/ipc/helpers/task-git';
import { isShuttingDown } from '../../src/main/shutdown-state';
import { IPC } from '../../src/shared/ipc-channels';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task } from '../../src/shared/types';

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'aaaa1111-0000-0000-0000-000000000000',
    display_id: 1,
    title: 'A task',
    ...overrides,
  } as Task;
}

function makeBlockedError(): BranchCheckoutBlockedError {
  return new BranchCheckoutBlockedError('/mock/project', 'blocking-task-id', 'Blocking task');
}

function makeContext(send: (...args: unknown[]) => void): IpcContext {
  return {
    mainWindow: { isDestroyed: () => false, webContents: { send } },
    currentProjectId: 'ambient-project',
  } as unknown as IpcContext;
}

/** The message argument of the single `send` call. */
function sentMessage(send: ReturnType<typeof vi.fn>): string {
  return send.mock.calls[0][3] as string;
}

describe('notifySpawnBlocked - project stamping', () => {
  it('sends with the EXPLICIT projectId when it differs from context.currentProjectId', () => {
    const send = vi.fn();
    const task = makeTask();
    const error = makeBlockedError();

    notifySpawnBlocked(makeContext(send), task, 'checkout', error, 'explicit-project');

    expect(send).toHaveBeenCalledWith(
      IPC.TASK_SPAWN_BLOCKED,
      task.id,
      task.title,
      error.message,
      'explicit-project',
    );
  });

  it('falls back to context.currentProjectId when no explicit projectId is passed', () => {
    const send = vi.fn();
    const task = makeTask();
    const error = makeBlockedError();

    notifySpawnBlocked(makeContext(send), task, 'checkout', error);

    expect(send).toHaveBeenCalledWith(
      IPC.TASK_SPAWN_BLOCKED,
      task.id,
      task.title,
      error.message,
      'ambient-project',
    );
  });
});

describe('notifySpawnBlocked - every failure reaches the user', () => {
  it('notifies for an arbitrary git failure at the worktree step', () => {
    const send = vi.fn();

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error("fatal: 'some-branch' is already used by worktree at '/repo'"),
      'explicit-project',
    );

    // Pre-fix this sent NOTHING, which is the whole #538 bug: the card looked
    // healthy and only a console line recorded the failure.
    expect(send).toHaveBeenCalledOnce();
    expect(sentMessage(send)).toContain('Worktree setup failed');
    expect(sentMessage(send)).toContain('already used by worktree');
  });

  it('notifies for an arbitrary git failure at the checkout step, naming that step', () => {
    const send = vi.fn();

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'checkout',
      new Error('error: Your local changes would be overwritten'),
      'explicit-project',
    );

    expect(send).toHaveBeenCalledOnce();
    // The step is what makes a vague git error actionable enough to act on.
    expect(sentMessage(send)).toContain('Branch checkout failed');
  });

  it('drops the step prefix when the error already names that step', () => {
    const send = vi.fn();

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      // The real shape of describeUnresolvableBase (git/base-branch.ts).
      new Error("Cannot create worktree: this task's base branch 'nope' does not exist."),
      'explicit-project',
    );

    // Otherwise it reads "Worktree setup failed: Cannot create worktree: ...",
    // which is both redundant and what pushed the toast past the viewport width.
    expect(sentMessage(send)).toBe("Cannot create worktree: this task's base branch 'nope' does not exist.");
  });

  it('keeps a BranchCheckoutBlockedError message verbatim, with no step prefix', () => {
    const send = vi.fn();
    const error = makeBlockedError();

    notifySpawnBlocked(makeContext(send), makeTask(), 'checkout', error, 'explicit-project');

    // It is already written for a user and names both blocker and remedy, so
    // prefixing it would only make it longer and worse.
    expect(sentMessage(send)).toBe(error.message);
  });

  it('sends only the FIRST line of a multi-line git error', () => {
    const send = vi.fn();

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error("fatal: the first line\nhint: a second line\nhint: a third line"),
      'explicit-project',
    );

    // Raw git errors run to many lines and would swamp a toast.
    expect(sentMessage(send)).toContain('fatal: the first line');
    expect(sentMessage(send)).not.toContain('a second line');
  });

  it('caps a pathologically long single-line error', () => {
    const send = vi.fn();

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error('x'.repeat(5000)),
      'explicit-project',
    );

    expect(sentMessage(send).length).toBeLessThan(400);
    expect(sentMessage(send)).toContain('...');
  });

  it('ends on a complete sentence rather than a dangling label', () => {
    const send = vi.fn();
    // The real shape: describeUnresolvableBase ends in a branch LIST, which is
    // exactly where a 200-char cut lands.
    const branches = Array.from({ length: 40 }, (_, index) => `feature/branch-number-${index}`).join(', ');

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error(
        "Cannot create worktree: this task's base branch 'nope' does not exist, locally or on origin. "
        + `Pick a different base branch for the task, or create the branch. Branches found: ${branches}`,
      ),
      'explicit-project',
    );

    const message = sentMessage(send);
    // The remediation sentence survives whole...
    expect(message).toContain('Pick a different base branch for the task, or create the branch.');
    // ...and the list is dropped cleanly rather than left as "Branches found:..."
    // (which promises a list and then shows nothing) or a half-printed name.
    expect(message).not.toContain('Branches found');
    expect(message.endsWith('.')).toBe(true);
    expect(message).not.toContain('...');
  });

  it('falls back to a word-boundary cut plus an ellipsis when there is no sentence to end on', () => {
    const send = vi.fn();
    const runOn = Array.from({ length: 60 }, (_, index) => `token${index}`).join(' ');

    notifySpawnBlocked(makeContext(send), makeTask(), 'worktree', new Error(runOn), 'explicit-project');

    const message = sentMessage(send);
    expect(message.endsWith('...')).toBe(true);
    // The ellipsis must not land mid-word.
    expect(message.slice(0, -3)).toMatch(/\d$/);
  });

  it('still names the step when the error carries no message at all', () => {
    const send = vi.fn();

    notifySpawnBlocked(makeContext(send), makeTask(), 'worktree', new Error(''), 'explicit-project');

    expect(sentMessage(send)).toBe('Worktree setup failed.');
  });

  it('handles a thrown non-Error value', () => {
    const send = vi.fn();

    notifySpawnBlocked(makeContext(send), makeTask(), 'worktree', 'a bare string', 'explicit-project');

    expect(sentMessage(send)).toContain('a bare string');
  });
});

describe('notifySpawnBlocked - window guards', () => {
  it('sends nothing when context.mainWindow is null', () => {
    const context = {
      mainWindow: null,
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;

    // Must not throw either: a removed null-guard would dereference
    // `context.mainWindow.isDestroyed()` on a null mainWindow.
    expect(() => notifySpawnBlocked(context, makeTask(), 'checkout', makeBlockedError(), 'explicit-project')).not.toThrow();
  });

  it('sends nothing when context.mainWindow.isDestroyed() returns true', () => {
    const send = vi.fn();
    const context = {
      mainWindow: { isDestroyed: () => true, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;

    notifySpawnBlocked(context, makeTask(), 'checkout', makeBlockedError(), 'explicit-project');

    expect(send).not.toHaveBeenCalled();
  });
});

describe('notifySpawnBlocked - shutdown guard', () => {
  it('sends nothing while the app is shutting down', () => {
    const send = vi.fn();
    // mockReturnValueOnce so this override applies to exactly this call and
    // later tests fall back to the mock's default (false) without needing
    // manual cleanup.
    vi.mocked(isShuttingDown).mockReturnValueOnce(true);

    // A quit that closes the DB or kills git mid-worktree surfaces as an
    // ordinary failure here. This holds even against a live, non-destroyed
    // window - the context below deliberately reports isDestroyed() === false,
    // so a removed shutdown guard cannot hide behind "the window was gone anyway".
    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error('The database connection is not open'),
      'explicit-project',
    );

    expect(send).not.toHaveBeenCalled();
  });

  it('still sends when the app is not shutting down', () => {
    const send = vi.fn();
    vi.mocked(isShuttingDown).mockReturnValueOnce(false);

    notifySpawnBlocked(
      makeContext(send),
      makeTask(),
      'worktree',
      new Error('some git failure'),
      'explicit-project',
    );

    expect(send).toHaveBeenCalledOnce();
  });
});
