/**
 * Unit tests for the TASK_CREATE IPC handler in task-crud.ts.
 *
 * Pattern mirrors bulk-delete-handler.test.ts: capture the function registered
 * with ipcMain.handle and invoke it directly. All dependencies are mocked so
 * no Electron binary or real filesystem is needed.
 *
 * task-lifecycle-lock is the REAL implementation so the withTaskLock wrap
 * added around TASK_CREATE's auto-spawn flow is observable.
 *
 * Covers:
 *   - auto_spawn=false on target lane: no ensureTaskWorktree, no transition,
 *     no auto-command; returns the created task
 *   - worktree error branch: ensureTaskWorktree throws, returns task with no
 *     spawn (lock is still acquired and released cleanly)
 *   - checkout error branch: ensureTaskBranchCheckout throws, returns task
 *     with no spawn
 *   - transition engine called with '*' wildcard as fromSwimlaneId
 *   - resumeSuspendedSession fallback: called when task has no session_id
 *     after executeTransition
 *   - auto-command scheduled when session exists and lane has auto_command
 *   - withTaskLock engagement: concurrent TASK_CREATE for the same task id
 *     serializes (second call waits for first)
 *   - no-project path: auto_spawn branch requires currentProjectId and
 *     currentProjectPath; null currentProjectPath short-circuits the block
 *   - pending attachments saved when provided
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

vi.mock('node:fs', () => ({
  default: {
    existsSync: vi.fn(() => false),
  },
}));

// p-queue is NOT mocked here. task-lifecycle-lock uses the real p-queue
// (concurrency:1) to provide actual serialization. Stubbing p-queue would
// cause withTaskLock to run all tasks inline (no queuing), which would make
// the lock-serialization assertion at the bottom of this file vacuously true.
// TASK_CREATE does not use PQueue directly (only TASK_BULK_DELETE does), so
// leaving p-queue real has no side effects here.

vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({})),
  default: vi.fn(() => ({})),
}));

vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn(() => ({})) }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {},
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    withLock = vi.fn(async (fn: () => Promise<unknown>) => fn());
    renameBranch = vi.fn(async () => null);
  },
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async () => 'main'),
}));

vi.mock('../../src/main/git/node-modules-link', () => ({
  linkNodeModules: vi.fn(),
  removeNodeModulesPath: vi.fn(),
}));

vi.mock('../../src/main/config/config-manager', () => ({
  ConfigManager: class {
    getEffectiveConfig = vi.fn(() => ({ git: { defaultBaseBranch: 'main' } }));
  },
}));

// task-lifecycle-lock: use the REAL implementation so lock semantics are preserved.
// TASK_CREATE wraps its auto-spawn flow in withTaskLock.

// Mocked helpers - configured per test
const mockGetProjectRepos = vi.fn();
const mockEnsureTaskWorktree = vi.fn(async () => null);
const mockEnsureTaskBranchCheckout = vi.fn(async () => {});
const mockBuildAutoCommandVars = vi.fn(() => ({}));
const mockCreateTransitionEngine = vi.fn();
const mockCleanupTaskResources = vi.fn(async () => {});

vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  buildAutoCommandVars: (...args: unknown[]) => mockBuildAutoCommandVars(...args),
  ensureTaskWorktree: (...args: unknown[]) => mockEnsureTaskWorktree(...args),
  ensureTaskBranchCheckout: (...args: unknown[]) => mockEnsureTaskBranchCheckout(...args),
  createTransitionEngine: (...args: unknown[]) => mockCreateTransitionEngine(...args),
  interpolateTemplate: vi.fn((template: string) => template),
  cleanupTaskResources: (...args: unknown[]) => mockCleanupTaskResources(...args),
  resolveSpawnOverrides: vi.fn((task: { model_override?: string | null; effort_override?: string | null } | undefined, lane: { model_override?: string | null; effort_override?: string | null } | null | undefined) => ({
    model: task?.model_override ?? lane?.model_override,
    effort: task?.effort_override ?? lane?.effort_override,
  })),
}));

vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((template: string) => template),
  resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
  execVersion: vi.fn(async () => '1.0.0'),
}));

vi.mock('../../src/main/ipc/handlers/task-move', () => ({
  guardActiveNonWorktreeSessions: vi.fn(),
  handleTaskMove: vi.fn(async () => {}),
}));

// ---------------------------------------------------------------------------
// Capture handlers registered by ipcMain.handle
// ---------------------------------------------------------------------------

const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();

// ---------------------------------------------------------------------------
// Import under test (after all mocks are registered)
// ---------------------------------------------------------------------------

import { registerTaskCrudHandlers } from '../../src/main/ipc/handlers/task-crud';
import { IPC } from '../../src/shared/ipc-channels';

// ---------------------------------------------------------------------------
// Helper types
// ---------------------------------------------------------------------------

interface MockTask {
  id: string;
  title: string;
  swimlane_id: string;
  worktree_path: string | null;
  session_id: string | null;
  branch_name: string | null;
  base_branch: string | null;
  /** Per-task auto_command (MCP-only, kangentic_create_task's autoCommand param).
   *  Wins over the destination swimlane's auto_command for this task only. */
  auto_command: string | null;
}

interface MockSwimlane {
  id: string;
  role: string | null;
  auto_spawn: boolean;
  auto_command: string | null;
  permission_mode: string | null;
}

interface MockTaskRepo {
  create: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
  list: ReturnType<typeof vi.fn>;
  delete: ReturnType<typeof vi.fn>;
}

interface MockAttachmentRepo {
  add: ReturnType<typeof vi.fn>;
  deleteByTaskId: ReturnType<typeof vi.fn>;
}

interface MockSwimlaneRepo {
  list: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
}

interface MockEngine {
  executeTransition: ReturnType<typeof vi.fn>;
  resumeSuspendedSession: ReturnType<typeof vi.fn>;
}

interface MockContext {
  currentProjectId: string | null;
  currentProjectPath: string | null;
  mainWindow: {
    isDestroyed: ReturnType<typeof vi.fn>;
    webContents: { send: ReturnType<typeof vi.fn> };
  };
  sessionManager: {
    listSessions: ReturnType<typeof vi.fn>;
    getActivityCache: ReturnType<typeof vi.fn>;
  };
  configManager: {
    getEffectiveConfig: ReturnType<typeof vi.fn>;
  };
  boardConfigManager: {
    getDefaultBaseBranch: ReturnType<typeof vi.fn>;
  };
  terminalSubmitScheduler: {
    scheduleKeystrokes: ReturnType<typeof vi.fn>;
  };
  projectRepo: {
    getById: ReturnType<typeof vi.fn>;
  };
}

function createMockTask(id: string, overrides: Partial<MockTask> = {}): MockTask {
  return {
    id,
    title: `Task ${id}`,
    swimlane_id: 'lane-doing',
    worktree_path: null,
    session_id: null,
    branch_name: null,
    base_branch: null,
    auto_command: null,
    ...overrides,
  };
}

function createMockSwimlane(id: string, overrides: Partial<MockSwimlane> = {}): MockSwimlane {
  return {
    id,
    role: null,
    auto_spawn: true,
    auto_command: null,
    permission_mode: null,
    ...overrides,
  };
}

function createMockTaskRepo(task: MockTask): MockTaskRepo {
  // Stored task reflects updates (e.g. session_id set by the engine)
  let storedTask = { ...task };
  return {
    create: vi.fn((_input: unknown) => storedTask),
    getById: vi.fn((_id: string) => storedTask),
    list: vi.fn(() => [storedTask]),
    delete: vi.fn(),
    // Test helper: allow tests to update the stored task between calls
    _setStoredTask: (updated: MockTask) => { storedTask = updated; },
  } as unknown as MockTaskRepo;
}

function createMockAttachmentRepo(): MockAttachmentRepo {
  return {
    add: vi.fn(),
    deleteByTaskId: vi.fn(),
  };
}

function createMockSwimlaneRepo(swimlanes: MockSwimlane[]): MockSwimlaneRepo {
  const laneMap = new Map(swimlanes.map((lane) => [lane.id, lane]));
  return {
    list: vi.fn(() => Array.from(laneMap.values())),
    getById: vi.fn((id: string) => laneMap.get(id) ?? null),
  };
}

function createMockEngine(): MockEngine {
  return {
    executeTransition: vi.fn(async () => {}),
    resumeSuspendedSession: vi.fn(async () => {}),
  };
}

function createMockContext(overrides: Partial<MockContext> = {}): MockContext {
  return {
    currentProjectId: 'proj-123',
    currentProjectPath: '/mock/project',
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      listSessions: vi.fn(() => []),
      getActivityCache: vi.fn(() => ({})),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' } })),
    },
    boardConfigManager: {
      getDefaultBaseBranch: vi.fn(() => null),
    },
    terminalSubmitScheduler: {
      scheduleKeystrokes: vi.fn(),
    },
    projectRepo: {
      getById: vi.fn(() => ({ id: 'proj-123', default_agent: 'claude', default_model: null, default_effort: null })),
    },
    ...overrides,
  };
}

async function callCreateHandler<T = unknown>(context: MockContext, input: Record<string, unknown>): Promise<T> {
  const handler = capturedHandlers.get(IPC.TASK_CREATE);
  if (!handler) throw new Error(`Handler for ${IPC.TASK_CREATE} was not registered`);
  return handler(null, input) as Promise<T>;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('TASK_CREATE handler', () => {
  let context: MockContext;
  let task: MockTask;
  let taskRepo: MockTaskRepo;
  let attachmentRepo: MockAttachmentRepo;
  let swimlaneRepo: MockSwimlaneRepo;
  let targetLane: MockSwimlane;

  beforeEach(() => {
    vi.clearAllMocks();
    capturedHandlers.clear();

    targetLane = createMockSwimlane('lane-doing', { auto_spawn: true });
    task = createMockTask('task-new', { swimlane_id: 'lane-doing' });
    taskRepo = createMockTaskRepo(task);
    attachmentRepo = createMockAttachmentRepo();
    swimlaneRepo = createMockSwimlaneRepo([targetLane]);
    context = createMockContext();

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    mockEnsureTaskWorktree.mockResolvedValue(null);
    mockEnsureTaskBranchCheckout.mockResolvedValue(undefined);

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    registerTaskCrudHandlers(context as never);
  });

  // =========================================================================
  // auto_spawn=false: skips entire lock block
  // =========================================================================

  it('skips worktree, transition, and auto-command when target lane has auto_spawn=false', async () => {
    const noSpawnLane = createMockSwimlane('lane-backlog', { auto_spawn: false });
    swimlaneRepo = createMockSwimlaneRepo([noSpawnLane]);
    const noSpawnTask = createMockTask('task-no-spawn', { swimlane_id: 'lane-backlog' });
    taskRepo = createMockTaskRepo(noSpawnTask);

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-backlog',
      title: 'No spawn task',
    });

    expect(result).toMatchObject({ id: 'task-no-spawn' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(context.terminalSubmitScheduler.scheduleKeystrokes).not.toHaveBeenCalled();
  });

  it('skips lock block when currentProjectPath is null', async () => {
    context.currentProjectPath = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No path task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
  });

  it('skips lock block when currentProjectId is null', async () => {
    context.currentProjectId = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No project task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Worktree error branch
  // =========================================================================

  it('returns task without spawning when ensureTaskWorktree throws (lock released cleanly)', async () => {
    mockEnsureTaskWorktree.mockRejectedValue(new Error('git worktree add failed'));

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Worktree error task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(context.terminalSubmitScheduler.scheduleKeystrokes).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Checkout error branch
  // =========================================================================

  it('returns task without spawning when ensureTaskBranchCheckout throws', async () => {
    mockEnsureTaskBranchCheckout.mockRejectedValue(new Error('branch locked by active session'));

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Checkout error task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(context.terminalSubmitScheduler.scheduleKeystrokes).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Transition engine called with '*' wildcard
  // =========================================================================

  it('calls executeTransition with "*" wildcard as fromSwimlaneId', async () => {
    const taskWithSession = { ...task, session_id: 'session-abc' };
    taskRepo.getById.mockReturnValue(taskWithSession);

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Wildcard transition task',
    });

    expect(engine.executeTransition).toHaveBeenCalledWith(
      expect.objectContaining({ id: 'task-new' }),
      '*',
      'lane-doing',
      targetLane.permission_mode,
      undefined, // skipPromptTemplate
      undefined, // signal
      undefined, // agentOverride
      // spawnOverrides: { model, effort } pulled from the destination swimlane
      // (undefined here because the mock swimlane fixture doesn't set them).
      { model: targetLane.model_override, effort: targetLane.effort_override },
    );
  });

  // =========================================================================
  // resumeSuspendedSession fallback
  // =========================================================================

  it('calls resumeSuspendedSession when task has no session_id after executeTransition', async () => {
    // getById returns task with no session_id (transition did not set one)
    taskRepo.getById.mockReturnValue({ ...task, session_id: null });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Resume fallback task',
    });

    expect(engine.resumeSuspendedSession).toHaveBeenCalledWith(
      expect.objectContaining({ id: 'task-new', session_id: null }),
      targetLane.permission_mode,
      undefined, // skipPromptTemplate
      undefined, // resumePrompt
      undefined, // signal
      undefined, // agentOverride
      undefined, // handoffPromptPrefix
      { model: targetLane.model_override, effort: targetLane.effort_override },
    );
  });

  it('does NOT call resumeSuspendedSession when task already has session_id after transition', async () => {
    // Simulate: transition engine set the session_id
    taskRepo.getById.mockReturnValue({ ...task, session_id: 'session-from-transition' });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No resume task',
    });

    expect(engine.resumeSuspendedSession).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Auto-command scheduling
  // =========================================================================

  it('schedules auto-command when session exists and lane has auto_command', async () => {
    const autoCommandLane = createMockSwimlane('lane-auto', {
      auto_spawn: true,
      auto_command: '/run-tests',
    });
    swimlaneRepo = createMockSwimlaneRepo([autoCommandLane]);
    const autoTask = createMockTask('task-auto', { swimlane_id: 'lane-auto' });
    taskRepo = createMockTaskRepo(autoTask);
    taskRepo.getById.mockReturnValue({ ...autoTask, session_id: 'session-auto' });

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-auto',
      title: 'Auto command task',
    });

    expect(context.terminalSubmitScheduler.scheduleKeystrokes).toHaveBeenCalledWith(
      'task-auto',
      'session-auto',
      ['/run-tests'],
      { freshlySpawned: true },
    );
  });

  it('does NOT schedule auto-command when finalTask has no session_id', async () => {
    const autoCommandLane = createMockSwimlane('lane-auto-nosession', {
      auto_spawn: true,
      auto_command: '/run-tests',
    });
    swimlaneRepo = createMockSwimlaneRepo([autoCommandLane]);
    const autoTask = createMockTask('task-no-session-auto', { swimlane_id: 'lane-auto-nosession' });
    taskRepo = createMockTaskRepo(autoTask);
    // Even after resumeSuspendedSession, getById returns task with no session_id
    taskRepo.getById.mockReturnValue({ ...autoTask, session_id: null });

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-auto-nosession',
      title: 'No session auto task',
    });

    expect(context.terminalSubmitScheduler.scheduleKeystrokes).not.toHaveBeenCalled();
  });

  it('does NOT schedule auto-command when lane has no auto_command', async () => {
    taskRepo.getById.mockReturnValue({ ...task, session_id: 'session-no-cmd' });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No auto command task',
    });

    // targetLane.auto_command is null
    expect(context.terminalSubmitScheduler.scheduleKeystrokes).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Per-task auto_command precedence (effectiveAutoCommand = finalTask?.auto_command
  // ?? toLane.auto_command). The task's value, set only via
  // kangentic_create_task's MCP-only autoCommand param, must win over the
  // destination column's auto_command for this task. Red-green: reverting
  // task-crud.ts's `finalTask?.auto_command ?? toLane.auto_command` to plain
  // `toLane.auto_command` makes the precedence test below fail (scheduler
  // would receive the lane's command instead of the task's); reverting the
  // `?? toLane.auto_command` fallback entirely makes the fallback test fail
  // (scheduler would not be called at all).
  // =========================================================================

  it('schedules the TASK auto_command, not the lane auto_command, when both are set (task wins)', async () => {
    const autoCommandLane = createMockSwimlane('lane-auto-both', {
      auto_spawn: true,
      auto_command: '/lane-command',
    });
    swimlaneRepo = createMockSwimlaneRepo([autoCommandLane]);
    const autoTask = createMockTask('task-auto-both', {
      swimlane_id: 'lane-auto-both',
      auto_command: '/task-command',
    });
    taskRepo = createMockTaskRepo(autoTask);
    taskRepo.getById.mockReturnValue({ ...autoTask, session_id: 'session-auto-both' });

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-auto-both',
      title: 'Task overrides lane auto command',
    });

    expect(context.terminalSubmitScheduler.scheduleKeystrokes).toHaveBeenCalledWith(
      'task-auto-both',
      'session-auto-both',
      ['/task-command'],
      { freshlySpawned: true },
    );
  });

  it('falls back to the lane auto_command when the task has none', async () => {
    const autoCommandLane = createMockSwimlane('lane-auto-fallback', {
      auto_spawn: true,
      auto_command: '/lane-command',
    });
    swimlaneRepo = createMockSwimlaneRepo([autoCommandLane]);
    const autoTask = createMockTask('task-auto-fallback', {
      swimlane_id: 'lane-auto-fallback',
      auto_command: null,
    });
    taskRepo = createMockTaskRepo(autoTask);
    taskRepo.getById.mockReturnValue({ ...autoTask, session_id: 'session-auto-fallback' });

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-auto-fallback',
      title: 'Task with no auto command falls back to lane',
    });

    expect(context.terminalSubmitScheduler.scheduleKeystrokes).toHaveBeenCalledWith(
      'task-auto-fallback',
      'session-auto-fallback',
      ['/lane-command'],
      { freshlySpawned: true },
    );
  });

  // =========================================================================
  // Pending attachments
  // =========================================================================

  it('saves pending attachments when provided', async () => {
    const pendingAttachments = [
      { filename: 'screenshot.png', data: 'base64data', media_type: 'image/png' },
    ];

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task with attachment',
      pendingAttachments,
    });

    expect(attachmentRepo.add).toHaveBeenCalledWith(
      '/mock/project',
      'task-new',
      'screenshot.png',
      'base64data',
      'image/png',
    );
  });

  it('does NOT save attachments when pendingAttachments is empty', async () => {
    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task no attachments',
      pendingAttachments: [],
    });

    expect(attachmentRepo.add).not.toHaveBeenCalled();
  });

  it('does NOT save attachments when currentProjectPath is null', async () => {
    context.currentProjectPath = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const pendingAttachments = [
      { filename: 'photo.jpg', data: 'data', media_type: 'image/jpeg' },
    ];

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task no project path',
      pendingAttachments,
    });

    expect(attachmentRepo.add).not.toHaveBeenCalled();
  });

  // =========================================================================
  // withTaskLock engagement: concurrent TASK_CREATE for the same task id
  // =========================================================================

  it('serializes concurrent withTaskLock calls for the same task id', async () => {
    // Use the hold pattern from task-lifecycle-lock.test.ts:
    // first invocation holds until released; second must wait.
    let releaseFirst!: () => void;
    const firstHold = new Promise<void>((resolve) => {
      releaseFirst = resolve;
    });
    const entryOrder: number[] = [];

    mockEnsureTaskWorktree.mockImplementation(async () => {
      entryOrder.push(entryOrder.length);
      if (entryOrder.length === 1) {
        await firstHold;
      }
    });

    // Both invocations share the same task.id returned by tasks.create.
    // That id is what withTaskLock keys on.
    taskRepo.getById.mockReturnValue({ ...task, session_id: null });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    const first = callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'First concurrent task',
    });
    const second = callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Second concurrent task',
    });

    // Only the first invocation should have entered ensureTaskWorktree yet
    await Promise.resolve();
    expect(entryOrder).toHaveLength(1);

    releaseFirst();
    await Promise.all([first, second]);

    // Both entered, in submission order
    expect(entryOrder).toHaveLength(2);
    expect(entryOrder).toEqual([0, 1]);
  });
});
