/**
 * Unit test for the remote-execution worktree skip added to
 * `ensureTaskWorktree` (task-git.ts): a task whose resolved agent is set to
 * 'remote' execution for the current project must not get a local worktree
 * created - the agent runs against the configured server directory instead.
 *
 * Also covers the `hasCommits` early-return guard `ensureTaskBranchCheckout`
 * keeps for itself: a repo with an unborn HEAD (no commits) has nothing to
 * branch from, so branch checkout would fail on the ref - the guard skips
 * that work entirely rather than letting the failure propagate.
 * `ensureTaskWorktree`'s own no-commits (and base-branch-resolution) guard
 * moved into `WorktreeManager.ensureWorktree` so every caller shares it; it
 * is covered by `tests/unit/worktree-base-branch.test.ts` instead, since
 * `WorktreeManager` is mocked away entirely in this file.
 *
 * WorktreeManager and git-checks are mocked entirely so this test never
 * touches git or the filesystem; it only asserts whether `ensureWorktree()` /
 * `checkoutBranch()` were called.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import path from 'node:path';
import { ensureTaskWorktree, ensureTaskBranchCheckout } from '../../src/main/ipc/helpers/task-git';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task, AppConfig, Project } from '../../src/shared/types';
import { DEFAULT_CONFIG } from '../../src/shared/types';

const ensureWorktreeMock = vi.fn().mockResolvedValue({ worktreePath: '/local/worktree/feature-x-abcd1234', branchName: 'feature-x' });
const checkoutBranchMock = vi.fn().mockResolvedValue(undefined);
const withLockMock = vi.fn((fn: () => unknown) => fn());

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: vi.fn().mockImplementation(function MockWorktreeManager(this: Record<string, unknown>) {
    this.withLock = withLockMock;
    this.ensureWorktree = ensureWorktreeMock;
    this.checkoutBranch = checkoutBranchMock;
  }),
}));

// hasCommits defaults to true (a normal, already-committed repo) so the pre-existing
// remote-execution-skip tests below exercise ONLY that branch, not this guard. Each
// hasCommits-guard test overrides it explicitly.
const hasCommitsMock = vi.fn().mockResolvedValue(true);
const isGitRepoMock = vi.fn().mockReturnValue(true);
const isAutoGeneratedBranchMock = vi.fn().mockReturnValue(false);

vi.mock('../../src/main/git/git-checks', () => ({
  hasCommits: (...args: unknown[]) => hasCommitsMock(...args),
  isGitRepo: (...args: unknown[]) => isGitRepoMock(...args),
  isAutoGeneratedBranch: (...args: unknown[]) => isAutoGeneratedBranchMock(...args),
  isInsideWorktree: vi.fn(() => true),
}));

// The base-branch checkout arm now freshens the checkout (simple-git instance
// plus a throttled fetch) before delegating to checkoutBranch. Neither belongs
// to this file's subject, so both are stubbed inert: the real simpleGit throws
// on this file's fictional '/project' cwd, and the fetch stub returns the bare
// branch name (the failure shape), which keeps the fast-forward path dormant.
vi.mock('simple-git', () => {
  const gitFactory = vi.fn(() => ({ raw: vi.fn(async () => '') }));
  return { simpleGit: gitFactory, default: gitFactory };
});

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async (_git: unknown, _path: string, branch: string) => branch),
}));

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-001',
    title: 'Fix the bug',
    description: '',
    swimlane_id: 'lane-1',
    position: 0,
    worktree_path: null,
    branch_name: null,
    base_branch: null,
    use_worktree: null,
    agent: null,
    agent_override: null,
    model_override: null,
    effort_override: null,
    permission_mode: null,
    session_id: null,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
    is_ghost: false,
    is_archived: false,
    priority: 0,
    display_id: 1,
    attachment_count: 0,
    labels: null,
    ...overrides,
  } as Task;
}

function makeConfig(overrides: Partial<AppConfig['agent']> = {}): AppConfig {
  return {
    ...DEFAULT_CONFIG,
    agent: { ...DEFAULT_CONFIG.agent, ...overrides },
  };
}

function makeContext(config: AppConfig, projects: Project[] = []): IpcContext {
  return {
    currentProjectPath: null,
    configManager: {
      getEffectiveConfig: vi.fn().mockReturnValue(config),
    },
    // resolveEffectiveBaseBranch consults the board default before the config
    // default; undefined = "no team-shared default", the common case.
    boardConfigManager: {
      getDefaultBaseBranchForPath: vi.fn(() => undefined),
    },
    mainWindow: { isDestroyed: () => false, webContents: { send: vi.fn() } },
    projectRepo: {
      list: vi.fn().mockReturnValue(projects),
    },
    // No live agents anywhere, so the checkout-occupancy guard inside
    // ensureTaskBranchCheckout is satisfied. That guard is covered by
    // branch-checkout-occupancy.test.ts.
    sessionManager: {
      listSessions: vi.fn().mockReturnValue([]),
    },
  } as unknown as IpcContext;
}

describe('ensureTaskWorktree - remote execution skip', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('creates a worktree normally when the resolved agent has no execution entry (local)', async () => {
    const context = makeContext(makeConfig());
    const task = makeTask({ agent_override: 'opencode' });

    await ensureTaskWorktree(context, task, makeTaskRepoStub(task) as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });

  it('skips worktree creation when the task-overridden agent is remote, and records why', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }));
    const task = makeTask({ agent_override: 'opencode' });
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(ensureWorktreeMock).not.toHaveBeenCalled();
    // The skip used to be silent. The reason is persisted (and mirrored onto the
    // in-memory task) so the renderer can say the agent is not in a worktree.
    expect(repo.setWorktreeSkipReason).toHaveBeenCalledWith('task-001', 'remote-agent');
    expect(task.worktree_skip_reason).toBe('remote-agent');
  });

  it('falls back to the project default agent when the task has no override', async () => {
    const context = makeContext(
      makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }),
      [{ path: '/project', default_agent: 'opencode' } as Project],
    );
    const task = makeTask({ agent_override: null });

    await ensureTaskWorktree(context, task, makeTaskRepoStub(task) as never, '/project');

    expect(ensureWorktreeMock).not.toHaveBeenCalled();
  });

  it('does not skip when a DIFFERENT agent is set to remote (task uses claude, opencode is remote)', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }));
    const task = makeTask({ agent_override: 'claude' });

    await ensureTaskWorktree(context, task, makeTaskRepoStub(task) as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });

  it('creates a worktree when the resolved agent is explicitly local', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'local', workingDirectory: null } } }));
    const task = makeTask({ agent_override: 'opencode' });

    await ensureTaskWorktree(context, task, makeTaskRepoStub(task) as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });
});

/**
 * The slice of TaskRepository `ensureTaskWorktree` touches: the legacy-folder
 * recovery it runs before creating, and the transactional write afterwards.
 * `recoverLegacyWorktreeFolder` returns null here - these tasks were never
 * created under the old `<slug>-<shortId>` scheme.
 */
function makeTaskRepoStub(task: unknown, overrides: Record<string, unknown> = {}) {
  return {
    update: vi.fn(),
    getById: vi.fn().mockReturnValue(task),
    recordWorktree: vi.fn(),
    setWorktreeSkipReason: vi.fn(),
    recoverLegacyWorktreeFolder: vi.fn(() => null),
    ...overrides,
  };
}

const SKIPPED_DISABLED = { skipped: true, reason: 'disabled' } as const;

describe('ensureTaskWorktree - ensureWorktree result passthrough', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('records a skipped ensureWorktree result as the task\'s skip reason, and nothing else', async () => {
    // ensureWorktree no longer needs its own hasCommits guard - it relies
    // entirely on WorktreeManager.ensureWorktree, which now names WHY it
    // created nothing (disabled / not a repo / nested worktree / no commits)
    // instead of collapsing them into one null. ensureTaskWorktree persists
    // that reason and mirrors it onto the caller's task object; it must not
    // touch the worktree columns.
    ensureWorktreeMock.mockResolvedValueOnce({ skipped: true, reason: 'no-commits' });
    const context = makeContext(makeConfig());
    const task = makeTask();
    const originalTask = { ...task };
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.recordWorktree).not.toHaveBeenCalled();
    expect(repo.setWorktreeSkipReason).toHaveBeenCalledWith('task-001', 'no-commits');
    expect(task).toEqual({ ...originalTask, worktree_skip_reason: 'no-commits' });
  });

  it('does not rewrite a skip reason the task already carries', async () => {
    ensureWorktreeMock.mockResolvedValueOnce(SKIPPED_DISABLED);
    const context = makeContext(makeConfig());
    const task = makeTask({ worktree_skip_reason: 'disabled' });
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.setWorktreeSkipReason).not.toHaveBeenCalled();
  });

  it('clears a stale skip reason when ensureWorktree reuses the existing worktree', async () => {
    // The reuse path is the one that must NOT be recorded as a skip: the task
    // demonstrably has a worktree, so a reason left over from an earlier
    // fallback would make the board claim it runs in the shared checkout.
    ensureWorktreeMock.mockResolvedValueOnce({ skipped: true, reason: 'reused' });
    const context = makeContext(makeConfig());
    const task = makeTask({ worktree_path: '/project/.kangentic/worktrees/1', worktree_skip_reason: 'disabled' });
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.recordWorktree).not.toHaveBeenCalled();
    expect(repo.setWorktreeSkipReason).toHaveBeenCalledWith('task-001', null);
    expect(task.worktree_skip_reason).toBeNull();
  });

  it('leaves a reused worktree alone when no stale reason exists', async () => {
    ensureWorktreeMock.mockResolvedValueOnce({ skipped: true, reason: 'reused' });
    const context = makeContext(makeConfig());
    const task = makeTask({ worktree_path: '/project/.kangentic/worktrees/1', worktree_skip_reason: null });
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.setWorktreeSkipReason).not.toHaveBeenCalled();
  });

  /**
   * The regression `worktree_folder` exists to prevent. A Done move nulls
   * `worktree_path`, so moving back out is a FRESH creation with no record of
   * where the task used to live. Without recovery, a task created before the
   * numeric scheme would be rebuilt at a different path, orphaning its agent
   * transcript (keyed by a slug of the cwd) and its browser cookie jar.
   */
  it('recovers a legacy folder from session history before creating, and hands it to ensureWorktree', async () => {
    ensureWorktreeMock.mockResolvedValueOnce(SKIPPED_DISABLED);
    const context = makeContext(makeConfig());
    const task = makeTask({ worktree_path: null, worktree_folder: null });
    const repo = makeTaskRepoStub(task, {
      recoverLegacyWorktreeFolder: vi.fn(() => 'dns-setup-4e41b16b'),
    });

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.recoverLegacyWorktreeFolder).toHaveBeenCalledWith(
      task.id,
      path.join('/project', '.kangentic', 'worktrees'),
    );
    expect(ensureWorktreeMock).toHaveBeenCalledWith(
      expect.objectContaining({ worktree_folder: 'dns-setup-4e41b16b' }),
      expect.anything(),
      expect.anything(),
    );
  });

  it('does not look for a legacy folder when the task already knows its own', async () => {
    ensureWorktreeMock.mockResolvedValueOnce(SKIPPED_DISABLED);
    const context = makeContext(makeConfig());
    const task = makeTask({ worktree_path: null, worktree_folder: '460' });
    const repo = makeTaskRepoStub(task);

    await ensureTaskWorktree(context, task, repo as never, '/project');

    expect(repo.recoverLegacyWorktreeFolder).not.toHaveBeenCalled();
  });

  it('propagates an ensureWorktree rejection (no try/catch inside ensureTaskWorktree)', async () => {
    const failure = new Error("Cannot create worktree: this task's base branch 'release-2.0' does not exist");
    ensureWorktreeMock.mockRejectedValueOnce(failure);
    const context = makeContext(makeConfig());
    const task = makeTask();

    await expect(
      ensureTaskWorktree(
        context,
        task,
        makeTaskRepoStub(task) as never,
        '/project',
      ),
    ).rejects.toThrow("Cannot create worktree: this task's base branch 'release-2.0' does not exist");
  });
});

describe('ensureTaskBranchCheckout - hasCommits guard', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('skips branch checkout entirely for a repo with no commits (unborn HEAD)', async () => {
    hasCommitsMock.mockResolvedValue(false);
    const task = makeTask({ worktree_path: null, branch_name: null, base_branch: 'main' });

    await ensureTaskBranchCheckout(makeContext(makeConfig()), task, '/project');

    expect(checkoutBranchMock).not.toHaveBeenCalled();
    expect(withLockMock).not.toHaveBeenCalled();
  });

  it('checks out the base branch once the repo has a commit (control case for the guard above)', async () => {
    // Same task/projectPath, only hasCommits differs - proves the skip above isn't
    // vacuous (e.g. via the "no base_branch" no-op further down).
    hasCommitsMock.mockResolvedValue(true);
    const task = makeTask({ worktree_path: null, branch_name: null, base_branch: 'main' });

    await ensureTaskBranchCheckout(makeContext(makeConfig()), task, '/project');

    expect(checkoutBranchMock).toHaveBeenCalledWith('main');
  });
});
