/**
 * Unit tests for the task-archive IPC handlers:
 *   TASK_LIST_ARCHIVED, TASK_UNARCHIVE, TASK_BULK_UNARCHIVE
 *
 * Pattern mirrors bulk-delete-handler.test.ts: capture the function registered
 * with ipcMain.handle and invoke it directly. All dependencies are mocked so
 * no Electron binary or real filesystem is needed.
 *
 * task-lifecycle-lock is the REAL implementation so lock serialization
 * behavior is observable in the TASK_UNARCHIVE / TASK_BULK_UNARCHIVE tests.
 *
 * Covers:
 *   TASK_LIST_ARCHIVED
 *     - delegates to tasks.listArchived() and returns the result
 *
 *   TASK_UNARCHIVE
 *     - no-project throw: throws when context.currentProjectId is null
 *     - auto_spawn=false early return: returns task without spawning
 *     - worktree error branch: ensureTaskWorktree throws, returns task, no spawn
 *     - checkout error branch: ensureTaskBranchCheckout throws, returns task, no spawn
 *     - no done-lane branch: skips transition engine when no role='done' lane
 *     - happy path: calls engine.executeTransition + schedules auto-command
 *     - resumeSuspendedSession fallback: called when no session_id after transition
 *     - withTaskLock serialization: concurrent calls for the same id serialize;
 *       different ids run independently
 *
 *   TASK_BULK_UNARCHIVE
 *     - auto_spawn=false lane skips spawn for every task in the batch
 *     - per-task worktree error is caught; subsequent tasks still process
 *     - per-iteration lock is independent per id (different ids don't block)
 *     - auto-command scheduled when finalTask.session_id and auto_command both set
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

// p-queue is NOT mocked here. task-lifecycle-lock uses the real p-queue
// (concurrency:1) to provide actual serialization. Stubbing p-queue would
// cause withTaskLock to run all tasks inline (no queuing), which would make
// the lock-serialization assertions vacuously pass or fail depending on the
// stub's implementation. task-archive.ts does not use PQueue directly, so
// there is no interference from leaving p-queue real.

vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({})),
  default: vi.fn(() => ({})),
}));

// DB layer - not exercised directly (getProjectRepos is mocked)
vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn(() => ({})) }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {},
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    withLock = vi.fn(async (fn: () => Promise<unknown>) => fn());
    removeWorktree = vi.fn(async () => true);
  },
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async () => 'main'),
}));

vi.mock('../../src/main/git/node-modules-link', () => ({
  linkNodeModules: vi.fn(),
  removeNodeModulesPath: vi.fn(),
}));

vi.mock('../../src/main/config/config-manager', () => ({
  ConfigManager: class {
    getEffectiveConfig = vi.fn(() => ({ git: { defaultBaseBranch: 'main' } }));
  },
}));

// task-lifecycle-lock: use the REAL implementation so lock semantics are preserved
// (TASK_UNARCHIVE and TASK_BULK_UNARCHIVE wrap each task in withTaskLock)

// Mocked helpers - configured per test
const mockGetProjectRepos = vi.fn();
const mockEnsureTaskWorktree = vi.fn(async () => null);
const mockEnsureTaskBranchCheckout = vi.fn(async () => {});
const mockBuildAutoCommandVars = vi.fn(() => ({}));
const mockCreateTransitionEngine = vi.fn();

vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  buildAutoCommandVars: (...args: unknown[]) => mockBuildAutoCommandVars(...args),
  ensureTaskWorktree: (...args: unknown[]) => mockEnsureTaskWorktree(...args),
  ensureTaskBranchCheckout: (...args: unknown[]) => mockEnsureTaskBranchCheckout(...args),
  createTransitionEngine: (...args: unknown[]) => mockCreateTransitionEngine(...args),
  interpolateTemplate: vi.fn((template: string) => template),
  cleanupTaskResources: vi.fn(async () => {}),
}));

vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((template: string) => template),
  resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
  execVersion: vi.fn(async () => '1.0.0'),
}));

vi.mock('../../src/main/ipc/handlers/task-move', () => ({
  guardActiveNonWorktreeSessions: vi.fn(),
  handleTaskMove: vi.fn(async () => {}),
}));

// ---------------------------------------------------------------------------
// Capture handlers registered by ipcMain.handle
// ---------------------------------------------------------------------------

const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();

// ---------------------------------------------------------------------------
// Import under test (after all mocks are registered)
// ---------------------------------------------------------------------------

import { registerTaskArchiveHandlers } from '../../src/main/ipc/handlers/task-archive';
import { IPC } from '../../src/shared/ipc-channels';

// ---------------------------------------------------------------------------
// Helper types
// ---------------------------------------------------------------------------

interface MockTask {
  id: string;
  title: string;
  swimlane_id: string;
  worktree_path: string | null;
  session_id: string | null;
  branch_name: string | null;
  base_branch: string | null;
}

interface MockSwimlane {
  id: string;
  role: string | null;
  auto_spawn: boolean;
  auto_command: string | null;
  permission_mode: string | null;
}

interface MockTaskRepo {
  listArchived: ReturnType<typeof vi.fn>;
  list: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
  unarchive: ReturnType<typeof vi.fn>;
}

interface MockSwimlaneRepo {
  list: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
}

interface MockEngine {
  executeTransition: ReturnType<typeof vi.fn>;
  resumeSuspendedSession: ReturnType<typeof vi.fn>;
}

interface MockContext {
  currentProjectId: string | null;
  currentProjectPath: string | null;
  mainWindow: {
    isDestroyed: ReturnType<typeof vi.fn>;
    webContents: { send: ReturnType<typeof vi.fn> };
  };
  sessionManager: {
    listSessions: ReturnType<typeof vi.fn>;
    getActivityCache: ReturnType<typeof vi.fn>;
  };
  configManager: {
    getEffectiveConfig: ReturnType<typeof vi.fn>;
  };
  boardConfigManager: {
    getDefaultBaseBranch: ReturnType<typeof vi.fn>;
  };
  commandInjector: {
    schedule: ReturnType<typeof vi.fn>;
  };
}

function createMockTask(id: string, overrides: Partial<MockTask> = {}): MockTask {
  return {
    id,
    title: `Task ${id}`,
    swimlane_id: 'lane-todo',
    worktree_path: null,
    session_id: null,
    branch_name: null,
    base_branch: null,
    ...overrides,
  };
}

function createMockSwimlane(id: string, overrides: Partial<MockSwimlane> = {}): MockSwimlane {
  return {
    id,
    role: null,
    auto_spawn: true,
    auto_command: null,
    permission_mode: null,
    ...overrides,
  };
}

function createMockTaskRepo(tasks: MockTask[]): MockTaskRepo {
  const taskMap = new Map(tasks.map((task) => [task.id, { ...task }]));
  return {
    listArchived: vi.fn(() => Array.from(taskMap.values())),
    list: vi.fn((_swimlaneId?: string) => Array.from(taskMap.values())),
    getById: vi.fn((id: string) => taskMap.get(id) ?? null),
    unarchive: vi.fn((id: string, targetSwimlaneId: string, _position: number) => {
      const task = taskMap.get(id);
      if (!task) throw new Error(`Task ${id} not found`);
      task.swimlane_id = targetSwimlaneId;
      return task;
    }),
  };
}

function createMockSwimlaneRepo(swimlanes: MockSwimlane[]): MockSwimlaneRepo {
  const laneMap = new Map(swimlanes.map((lane) => [lane.id, lane]));
  return {
    list: vi.fn(() => Array.from(laneMap.values())),
    getById: vi.fn((id: string) => laneMap.get(id) ?? null),
  };
}

function createMockEngine(): MockEngine {
  return {
    executeTransition: vi.fn(async () => {}),
    resumeSuspendedSession: vi.fn(async () => {}),
  };
}

function createMockContext(overrides: Partial<MockContext> = {}): MockContext {
  return {
    currentProjectId: 'proj-123',
    currentProjectPath: '/mock/project',
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      listSessions: vi.fn(() => []),
      getActivityCache: vi.fn(() => ({})),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' } })),
    },
    boardConfigManager: {
      getDefaultBaseBranch: vi.fn(() => null),
    },
    commandInjector: {
      schedule: vi.fn(),
    },
    ...overrides,
  };
}

// Invoke a captured handler directly. The first argument (Electron Event
// object) is unused by all three archive handlers - pass null as a stand-in.
async function callHandler<T = unknown>(channel: string, ...args: unknown[]): Promise<T> {
  const handler = capturedHandlers.get(channel);
  if (!handler) throw new Error(`Handler for ${channel} was not registered`);
  return handler(null, ...args) as Promise<T>;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('task-archive handlers', () => {
  let context: MockContext;
  let taskRepo: MockTaskRepo;
  let swimlaneRepo: MockSwimlaneRepo;

  // Swimlanes used across most tests:
  //   - doneLane: role='done' (the source for unarchive transitions)
  //   - targetLane: auto_spawn=true (default happy path target)
  let doneLane: MockSwimlane;
  let targetLane: MockSwimlane;

  beforeEach(() => {
    vi.clearAllMocks();
    capturedHandlers.clear();

    doneLane = createMockSwimlane('lane-done', { role: 'done', auto_spawn: false });
    targetLane = createMockSwimlane('lane-doing', { role: null, auto_spawn: true });

    context = createMockContext();

    taskRepo = createMockTaskRepo([]);
    swimlaneRepo = createMockSwimlaneRepo([doneLane, targetLane]);

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: { deleteByTaskId: vi.fn() },
    });

    mockEnsureTaskWorktree.mockResolvedValue(null);
    mockEnsureTaskBranchCheckout.mockResolvedValue(undefined);

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    // The `as never` cast sidesteps the full IpcContext shape requirement.
    // Only the subset used by task-archive handlers is provided.
    registerTaskArchiveHandlers(context as never);
  });

  // =========================================================================
  // TASK_LIST_ARCHIVED
  // =========================================================================

  describe('TASK_LIST_ARCHIVED', () => {
    it('delegates to tasks.listArchived() and returns the result', async () => {
      const archived = [
        createMockTask('task-a'),
        createMockTask('task-b'),
      ];
      taskRepo.listArchived.mockReturnValue(archived);

      const result = await callHandler(IPC.TASK_LIST_ARCHIVED);

      expect(taskRepo.listArchived).toHaveBeenCalledTimes(1);
      expect(result).toEqual(archived);
    });

    it('returns an empty array when there are no archived tasks', async () => {
      taskRepo.listArchived.mockReturnValue([]);

      const result = await callHandler(IPC.TASK_LIST_ARCHIVED);

      expect(result).toEqual([]);
    });
  });

  // =========================================================================
  // TASK_UNARCHIVE
  // =========================================================================

  describe('TASK_UNARCHIVE', () => {
    it('throws when context.currentProjectId is null', async () => {
      context.currentProjectId = null;
      // Re-register with the updated context so the handler closure captures null
      capturedHandlers.clear();
      registerTaskArchiveHandlers(context as never);

      await expect(
        callHandler(IPC.TASK_UNARCHIVE, { id: 'task-1', targetSwimlaneId: 'lane-doing' }),
      ).rejects.toThrow('No project is currently open');
    });

    it('returns task without spawning when target lane has auto_spawn=false', async () => {
      const noSpawnLane = createMockSwimlane('lane-backlog', { auto_spawn: false });
      swimlaneRepo = createMockSwimlaneRepo([doneLane, noSpawnLane]);
      const task = createMockTask('task-nospawn');
      taskRepo = createMockTaskRepo([task]);

      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const result = await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-nospawn',
        targetSwimlaneId: 'lane-backlog',
      });

      expect(result).toMatchObject({ id: 'task-nospawn' });
      expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
      expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    it('returns task without spawning when ensureTaskWorktree throws', async () => {
      const task = createMockTask('task-worktree-err');
      taskRepo = createMockTaskRepo([task]);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      mockEnsureTaskWorktree.mockRejectedValue(new Error('git worktree add failed'));

      const result = await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-worktree-err',
        targetSwimlaneId: 'lane-doing',
      });

      expect(result).toMatchObject({ id: 'task-worktree-err' });
      expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    it('returns task without spawning when ensureTaskBranchCheckout throws', async () => {
      const task = createMockTask('task-checkout-err');
      taskRepo = createMockTaskRepo([task]);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      mockEnsureTaskWorktree.mockResolvedValue(null);
      mockEnsureTaskBranchCheckout.mockRejectedValue(new Error('branch locked by active session'));

      const result = await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-checkout-err',
        targetSwimlaneId: 'lane-doing',
      });

      expect(result).toMatchObject({ id: 'task-checkout-err' });
      expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    it('skips transition engine when no role=done lane exists', async () => {
      // Swimlanes with no role='done' entry
      const noRoleSwimlaneRepo = createMockSwimlaneRepo([
        createMockSwimlane('lane-a', { role: 'todo' }),
        targetLane,
      ]);
      const task = createMockTask('task-no-done');
      taskRepo = createMockTaskRepo([task]);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: noRoleSwimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const result = await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-no-done',
        targetSwimlaneId: 'lane-doing',
      });

      expect(result).toMatchObject({ id: 'task-no-done' });
      expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    it('calls executeTransition with doneLane -> targetSwimlaneId on happy path', async () => {
      const task = createMockTask('task-happy');
      // After transition, getById returns a task with a session_id set
      const taskWithSession = { ...task, session_id: 'session-abc' };
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue(taskWithSession);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-happy',
        targetSwimlaneId: 'lane-doing',
      });

      expect(engine.executeTransition).toHaveBeenCalledWith(
        expect.objectContaining({ id: 'task-happy' }),
        doneLane.id,
        'lane-doing',
        targetLane.permission_mode,
        true,
      );
    });

    it('calls resumeSuspendedSession when task has no session_id after transition', async () => {
      // getById returns a task with no session_id even after executeTransition
      const task = createMockTask('task-no-session');
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue({ ...task, session_id: null });
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-no-session',
        targetSwimlaneId: 'lane-doing',
      });

      expect(engine.resumeSuspendedSession).toHaveBeenCalledWith(
        expect.objectContaining({ id: 'task-no-session' }),
        targetLane.permission_mode,
        true,
      );
    });

    it('does NOT call resumeSuspendedSession when task already has a session_id after transition', async () => {
      const task = createMockTask('task-has-session');
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue({ ...task, session_id: 'session-existing' });
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-has-session',
        targetSwimlaneId: 'lane-doing',
      });

      expect(engine.resumeSuspendedSession).not.toHaveBeenCalled();
    });

    it('schedules auto-command when finalTask has session_id and lane has auto_command', async () => {
      const autoCommandLane = createMockSwimlane('lane-auto', {
        auto_spawn: true,
        auto_command: '/run-tests',
      });
      swimlaneRepo = createMockSwimlaneRepo([doneLane, autoCommandLane]);
      const task = createMockTask('task-auto-cmd');
      const taskWithSession = { ...task, session_id: 'session-xyz' };
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue(taskWithSession);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-auto-cmd',
        targetSwimlaneId: 'lane-auto',
      });

      expect(context.commandInjector.schedule).toHaveBeenCalledWith(
        'task-auto-cmd',
        'session-xyz',
        '/run-tests',
        { freshlySpawned: true },
      );
    });

    it('does NOT schedule auto-command when lane has no auto_command', async () => {
      const task = createMockTask('task-no-cmd');
      const taskWithSession = { ...task, session_id: 'session-noncmd' };
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue(taskWithSession);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-no-cmd',
        targetSwimlaneId: 'lane-doing',
      });

      // targetLane.auto_command is null
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    // -----------------------------------------------------------------------
    // Lock serialization: concurrent TASK_UNARCHIVE calls for the same task id
    // must complete in submission order; different ids run independently.
    // -----------------------------------------------------------------------

    it('serializes concurrent TASK_UNARCHIVE calls for the same task id', async () => {
      // Use a hold mechanism to control call timing:
      // - first invocation: holds until we release it
      // - second invocation: should queue behind the first
      let releaseFirstUnarchive!: () => void;
      const firstHold = new Promise<void>((resolve) => {
        releaseFirstUnarchive = resolve;
      });
      const entryOrder: number[] = [];

      mockEnsureTaskWorktree.mockImplementation(async () => {
        entryOrder.push(entryOrder.length);
        if (entryOrder.length === 1) {
          await firstHold;
        }
      });

      // Both tasks have the same id - must serialize
      const task = createMockTask('task-concurrent');
      taskRepo = createMockTaskRepo([task]);
      taskRepo.getById.mockReturnValue({ ...task, session_id: null });
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: createMockSwimlaneRepo([doneLane, targetLane]),
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      const first = callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-concurrent',
        targetSwimlaneId: 'lane-doing',
      });
      const second = callHandler(IPC.TASK_UNARCHIVE, {
        id: 'task-concurrent',
        targetSwimlaneId: 'lane-doing',
      });

      // Only the first call should have entered ensureTaskWorktree so far
      await Promise.resolve(); // flush one microtask tick
      expect(entryOrder).toHaveLength(1);

      // Release the first; the second should now proceed
      releaseFirstUnarchive();
      await Promise.all([first, second]);

      // Both entered, in order
      expect(entryOrder).toHaveLength(2);
      expect(entryOrder).toEqual([0, 1]);
    });

    it('runs TASK_UNARCHIVE concurrently for different task ids', async () => {
      // Each call holds for a fixed delay; if they ran serially the total
      // elapsed time would be ~2x the delay. Parallelism collapses it to ~1x.
      const DELAY_MS = 40;
      let holdCount = 0;

      mockEnsureTaskWorktree.mockImplementation(async () => {
        holdCount += 1;
        await new Promise((resolve) => setTimeout(resolve, DELAY_MS));
      });

      const taskA = createMockTask('task-parallel-a');
      const taskB = createMockTask('task-parallel-b');
      const mixedTaskRepo = createMockTaskRepo([taskA, taskB]);
      mixedTaskRepo.getById.mockImplementation((id: string) => {
        return id === 'task-parallel-a' ? taskA : taskB;
      });
      mockGetProjectRepos.mockReturnValue({
        tasks: mixedTaskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      const start = Date.now();
      await Promise.all([
        callHandler(IPC.TASK_UNARCHIVE, { id: 'task-parallel-a', targetSwimlaneId: 'lane-doing' }),
        callHandler(IPC.TASK_UNARCHIVE, { id: 'task-parallel-b', targetSwimlaneId: 'lane-doing' }),
      ]);
      const elapsed = Date.now() - start;

      // Both entered ensureTaskWorktree
      expect(holdCount).toBe(2);
      // If serialized, elapsed >= 2 * DELAY_MS; parallel keeps it under 1.5x
      expect(elapsed).toBeLessThan(DELAY_MS * 1.5 + 30); // 30ms scheduler headroom
    });
  });

  // =========================================================================
  // TASK_BULK_UNARCHIVE
  // =========================================================================

  describe('TASK_BULK_UNARCHIVE', () => {
    it('throws when context.currentProjectId is null', async () => {
      context.currentProjectId = null;
      capturedHandlers.clear();
      registerTaskArchiveHandlers(context as never);

      await expect(
        callHandler(IPC.TASK_BULK_UNARCHIVE, ['task-1', 'task-2'], 'lane-doing'),
      ).rejects.toThrow('No project is currently open');
    });

    it('skips spawn for all tasks when target lane has auto_spawn=false', async () => {
      const noSpawnLane = createMockSwimlane('lane-backlog', { auto_spawn: false });
      swimlaneRepo = createMockSwimlaneRepo([doneLane, noSpawnLane]);
      const tasks = [
        createMockTask('task-bulk-a'),
        createMockTask('task-bulk-b'),
      ];
      taskRepo = createMockTaskRepo(tasks);
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      await callHandler(IPC.TASK_BULK_UNARCHIVE, ['task-bulk-a', 'task-bulk-b'], 'lane-backlog');

      // unarchive called for each task
      expect(taskRepo.unarchive).toHaveBeenCalledTimes(2);
      // ensureTaskWorktree must NOT have been called (auto_spawn=false short-circuits)
      expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
      expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });

    it('continues processing subsequent tasks when one worktree creation fails', async () => {
      const tasks = [
        createMockTask('task-fail-worktree'),
        createMockTask('task-succeed'),
      ];
      taskRepo = createMockTaskRepo(tasks);
      taskRepo.getById.mockImplementation((id: string) => {
        const found = tasks.find((t) => t.id === id);
        return found ? { ...found, session_id: id === 'task-succeed' ? 'session-ok' : null } : null;
      });
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      // First call throws, second succeeds
      mockEnsureTaskWorktree
        .mockRejectedValueOnce(new Error('worktree locked'))
        .mockResolvedValueOnce(null);

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      // Should not throw - per-task errors are caught
      await expect(
        callHandler(IPC.TASK_BULK_UNARCHIVE, ['task-fail-worktree', 'task-succeed'], 'lane-doing'),
      ).resolves.toBeUndefined();

      // The second task still proceeded to ensureTaskWorktree
      expect(mockEnsureTaskWorktree).toHaveBeenCalledTimes(2);
      // Transition engine called for the successful task only
      expect(engine.executeTransition).toHaveBeenCalledTimes(1);
    });

    it('processes each task with an independent lock (different ids do not block each other)', async () => {
      // Two tasks with different ids are processed in the for-loop. Even though
      // each uses withTaskLock, different ids have independent queues so they
      // do not wait on each other. The for-loop is sequential by await, but
      // the LOCK overhead should not add cumulative delay across different ids.
      const tasks = [
        createMockTask('task-ind-a'),
        createMockTask('task-ind-b'),
      ];
      taskRepo = createMockTaskRepo(tasks);
      taskRepo.getById.mockReturnValue({ ...tasks[0], session_id: null });
      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      // Just verify both unarchive calls happen - the independence assertion
      // for bulk is at the for-loop level (sequential by design), not parallel
      await callHandler(IPC.TASK_BULK_UNARCHIVE, ['task-ind-a', 'task-ind-b'], 'lane-doing');

      expect(taskRepo.unarchive).toHaveBeenCalledTimes(2);
      expect(engine.executeTransition).toHaveBeenCalledTimes(2);
    });

    it('schedules auto-command per task when finalTask has session_id and lane has auto_command', async () => {
      const autoCommandLane = createMockSwimlane('lane-auto-bulk', {
        auto_spawn: true,
        auto_command: '/run-ci',
      });
      swimlaneRepo = createMockSwimlaneRepo([doneLane, autoCommandLane]);

      const tasks = [
        createMockTask('task-bulk-cmd-a'),
        createMockTask('task-bulk-cmd-b'),
      ];
      taskRepo = createMockTaskRepo(tasks);

      // Each getById returns the task with a session_id
      taskRepo.getById.mockImplementation((id: string) => {
        const found = tasks.find((t) => t.id === id);
        return found ? { ...found, session_id: `session-${id}` } : null;
      });

      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(
        IPC.TASK_BULK_UNARCHIVE,
        ['task-bulk-cmd-a', 'task-bulk-cmd-b'],
        'lane-auto-bulk',
      );

      expect(context.commandInjector.schedule).toHaveBeenCalledTimes(2);
      expect(context.commandInjector.schedule).toHaveBeenCalledWith(
        'task-bulk-cmd-a',
        'session-task-bulk-cmd-a',
        '/run-ci',
        { freshlySpawned: true },
      );
      expect(context.commandInjector.schedule).toHaveBeenCalledWith(
        'task-bulk-cmd-b',
        'session-task-bulk-cmd-b',
        '/run-ci',
        { freshlySpawned: true },
      );
    });

    it('skips auto-command when task has no session_id after resumeSuspendedSession', async () => {
      const autoCommandLane = createMockSwimlane('lane-auto-skip', {
        auto_spawn: true,
        auto_command: '/do-something',
      });
      swimlaneRepo = createMockSwimlaneRepo([doneLane, autoCommandLane]);

      const task = createMockTask('task-no-session-bulk');
      taskRepo = createMockTaskRepo([task]);
      // getById always returns the task with NO session_id
      taskRepo.getById.mockReturnValue({ ...task, session_id: null });

      mockGetProjectRepos.mockReturnValue({
        tasks: taskRepo,
        swimlanes: swimlaneRepo,
        actions: { getTransitionsFor: vi.fn(() => []) },
        attachments: { deleteByTaskId: vi.fn() },
      });

      const engine = createMockEngine();
      mockCreateTransitionEngine.mockReturnValue(engine);

      await callHandler(
        IPC.TASK_BULK_UNARCHIVE,
        ['task-no-session-bulk'],
        'lane-auto-skip',
      );

      // resumeSuspendedSession should have been called (no session after transition)
      expect(engine.resumeSuspendedSession).toHaveBeenCalledTimes(1);
      // But schedule must NOT be called since finalTask.session_id is still null
      expect(context.commandInjector.schedule).not.toHaveBeenCalled();
    });
  });
});
