/**
 * Gap-3 surfacing: when a spawn REUSES a pre-existing worktree
 * (ensureWorktree returns null because the tree is alive on disk), the spawn
 * must not silently run on a tree cut from an old base. ensureTaskWorktree
 * fires a fire-and-forget drift probe: throttled base fetch, one rev-list
 * against origin/<effective base> with the WORKTREE as cwd, and a sticky
 * spawn-progress note when behind. The probe must never block or fail the
 * spawn, and must not fire for any other ensureWorktree null reason.
 *
 * spawn-progress is deliberately the REAL module here so these tests pin the
 * actual decorated labels the card renders.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { BrowserWindow } from 'electron';

const { mockEnsureWorktree, mockFetchIfStale, mockRunGitWithTimeout, mockRefResolvesLocally, mockIsInsideWorktree } = vi.hoisted(() => ({
  mockEnsureWorktree: vi.fn(),
  mockFetchIfStale: vi.fn(),
  mockRunGitWithTimeout: vi.fn(),
  mockRefResolvesLocally: vi.fn(async () => true),
  mockIsInsideWorktree: vi.fn(() => true),
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  // The probe queues its git work on the static per-project git lock at
  // background priority; pass-through here, like the instance lock.
  GitQueuePriority: { USER: 0, BACKGROUND: 10 },
  WorktreeManager: class {
    constructor(public projectPath: string) {}
    static withGitLock<T>(_projectPath: string, operation: () => Promise<T>): Promise<T> { return operation(); }
    withLock<T>(operation: () => Promise<T>): Promise<T> { return operation(); }
    ensureWorktree(...args: unknown[]): unknown { return mockEnsureWorktree(...args); }
  },
}));

vi.mock('../../src/main/git/task-worktree-folder', () => ({
  prepareWorktreeFolder: vi.fn(),
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isGitRepo: vi.fn(() => true),
  hasCommits: vi.fn(async () => true),
  isAutoGeneratedBranch: vi.fn(() => false),
  isInsideWorktree: mockIsInsideWorktree,
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: mockFetchIfStale,
}));

vi.mock('../../src/main/git/base-branch', () => ({
  refResolvesLocally: mockRefResolvesLocally,
}));

vi.mock('../../src/main/git/git-spawn', () => ({
  runGitWithTimeout: mockRunGitWithTimeout,
  isGitTimeoutError: vi.fn(() => false),
}));

vi.mock('simple-git', () => ({
  default: () => ({}),
}));

vi.mock('node:fs', () => ({
  default: {
    existsSync: vi.fn(() => true),
  },
}));

vi.mock('../../src/main/shutdown-state', () => ({
  isShuttingDown: vi.fn(() => false),
  setShuttingDown: vi.fn(),
}));

import { ensureTaskWorktree, __resetSpawnWarningCooldownsForTest } from '../../src/main/ipc/helpers/task-git';
import {
  emitSpawnProgress,
  getInFlightSpawnProgress,
  __resetSpawnProgressForTest,
} from '../../src/main/transition-engine/spawn-progress';
import { IPC } from '../../src/shared/ipc-channels';
import type { FetchIfStaleOutcome } from '../../src/main/git/fetch-throttle';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task } from '../../src/shared/types';
import type { TaskRepository } from '../../src/main/db/repositories/task-repository';

const WORKTREE_PATH = '/project/.kangentic/worktrees/7';

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-aaaa-0000',
    display_id: 7,
    title: 'Reused task',
    swimlane_id: 'lane-1',
    worktree_path: WORKTREE_PATH,
    branch_name: 'reused-task-task-aaa',
    base_branch: null,
    use_worktree: 1,
    session_id: null,
    ...overrides,
  } as Task;
}

function makeContext(): { context: IpcContext; window: BrowserWindow; send: ReturnType<typeof vi.fn> } {
  const send = vi.fn();
  const window = { isDestroyed: () => false, webContents: { send } } as unknown as BrowserWindow;
  const context = {
    mainWindow: window,
    currentProjectId: null,
    currentProjectPath: null,
    sessionManager: { listSessions: () => [] },
    projectRepo: { list: () => [] },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({
        agent: { execution: {} },
        git: { worktreesEnabled: true, defaultBaseBranch: 'main', copyFiles: [] },
      })),
    },
    boardConfigManager: { getDefaultBaseBranchForPath: vi.fn((): string | undefined => undefined) },
  } as unknown as IpcContext;
  return { context, window, send };
}

const stubTasksRepo = {
  recordWorktree: vi.fn(),
  getById: vi.fn(() => makeTask()),
} as unknown as TaskRepository;

/** fetchIfStale succeeds: reports 'fetched' and returns the origin ref. */
function fetchSucceeds(): void {
  mockFetchIfStale.mockImplementation(async (
    _git: unknown, _path: string, branch: string,
    options?: { onOutcome?: (outcome: FetchIfStaleOutcome) => void },
  ) => {
    options?.onOutcome?.({ kind: 'fetched' });
    return `origin/${branch}`;
  });
}

/** The rev-list output is "<behind>\t<ahead>". */
function revListReturns(behind: number, ahead: number): void {
  mockRunGitWithTimeout.mockResolvedValue({ stdout: `${behind}\t${ahead}\n`, stderr: '' });
}

describe('worktree reuse drift probe', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    __resetSpawnProgressForTest();
    __resetSpawnWarningCooldownsForTest();
    mockEnsureWorktree.mockResolvedValue(null);
    mockRefResolvesLocally.mockResolvedValue(true);
    mockIsInsideWorktree.mockReturnValue(true);
    fetchSucceeds();
    revListReturns(0, 0);
  });

  it('a behind worktree pins a "base N behind" note on the in-flight spawn label', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    revListReturns(3, 1);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent... (base 3 behind)');
    });
  });

  it('runs the rev-list with the WORKTREE as cwd against origin/<effective base>', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    revListReturns(2, 0);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      expect(mockRunGitWithTimeout).toHaveBeenCalledWith(
        WORKTREE_PATH,
        ['rev-list', '--left-right', '--count', 'origin/main...HEAD'],
        expect.objectContaining({ timeoutMs: 5_000 }),
      );
    });
  });

  it('uses the task\'s own base_branch when set', async () => {
    const { context, window } = makeContext();
    const task = makeTask({ base_branch: 'release/2.0' });
    emitSpawnProgress(window, task.id, 'starting-agent');
    revListReturns(1, 0);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      expect(mockRunGitWithTimeout).toHaveBeenCalledWith(
        WORKTREE_PATH,
        ['rev-list', '--left-right', '--count', 'origin/release/2.0...HEAD'],
        expect.objectContaining({ timeoutMs: 5_000 }),
      );
      expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent... (base 1 behind)');
    });
  });

  it('an up-to-date worktree leaves the label undecorated', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    revListReturns(0, 2);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    // The probe is async; wait for the rev-list to have run, THEN assert the
    // label stayed clean (a bare negative assertion would pass vacuously
    // before the probe finished).
    await vi.waitFor(() => {
      expect(mockRunGitWithTimeout).toHaveBeenCalled();
    });
    expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent...');
  });

  it('a fetch failure sets the "base fetch failed" note and pushes the spawn warning, and never throws', async () => {
    const { context, window, send } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockFetchIfStale.mockImplementation(async (
      _git: unknown, _path: string, branch: string,
      options?: { onOutcome?: (outcome: FetchIfStaleOutcome) => void },
    ) => {
      options?.onOutcome?.({ kind: 'failed', reason: 'network', message: 'fatal: Could not resolve host: github.com' });
      return branch;
    });

    await expect(ensureTaskWorktree(context, task, stubTasksRepo, '/project')).resolves.toBeUndefined();

    await vi.waitFor(() => {
      expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent... (base fetch failed)');
      expect(send).toHaveBeenCalledWith(
        IPC.TASK_SPAWN_WARNING,
        task.id,
        expect.stringContaining("could not fetch latest 'main' from origin (network unreachable)"),
        undefined,
      );
    });
  });

  // makeBaseFetchOutcomeHandler's reason-class filtering (task-git.ts): the
  // silent classes (abort / no-remote / branch-missing) must set no stale note
  // and push no spawn warning at all - a throttle skip or "always local"
  // outcome is not staleness, and an abort is the user cancelling. Driven
  // through the real ensureTaskWorktree -> surfaceWorktreeBaseDrift ->
  // makeBaseFetchOutcomeHandler chain, the way the 'network' failure test above
  // already does for the toasting classes.
  it.each([
    ['abort', 'aborted before spawn'],
    ['no-remote', 'does not appear to be a git repository'],
    ['branch-missing', "couldn't find remote ref main"],
  ] as const)('a %s fetch failure sets no stale note and pushes no spawn warning', async (reason, message) => {
    const { context, window, send } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockFetchIfStale.mockImplementation(async (
      _git: unknown, _path: string, branch: string,
      options?: { onOutcome?: (outcome: FetchIfStaleOutcome) => void },
    ) => {
      options?.onOutcome?.({ kind: 'failed', reason, message });
      return branch;
    });

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    // Anchor on the probe actually finishing (it continues past the failed
    // fetch because refResolvesLocally defaults to true) so the assertions
    // below cannot pass vacuously before the outcome handler has even run.
    await vi.waitFor(() => {
      expect(mockRunGitWithTimeout).toHaveBeenCalled();
    });
    expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent...');
    // `send` also carries TASK_SPAWN_PROGRESS pushes from emitSpawnProgress
    // above, so filter to the warning channel specifically.
    const warningCalls = send.mock.calls.filter((call) => call[0] === IPC.TASK_SPAWN_WARNING);
    expect(warningCalls).toHaveLength(0);
  });

  it('an "other" fetch failure sets the "base fetch failed" note but never toasts (no FETCH_FAILURE_PHRASES entry)', async () => {
    const { context, window, send } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockFetchIfStale.mockImplementation(async (
      _git: unknown, _path: string, branch: string,
      options?: { onOutcome?: (outcome: FetchIfStaleOutcome) => void },
    ) => {
      options?.onOutcome?.({ kind: 'failed', reason: 'other', message: 'fatal: unexpected git error' });
      return branch;
    });

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent... (base fetch failed)');
    });
    const warningCalls = send.mock.calls.filter((call) => call[0] === IPC.TASK_SPAWN_WARNING);
    expect(warningCalls).toHaveLength(0);
  });

  it('skips the rev-list when origin/<base> does not resolve locally', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockRefResolvesLocally.mockResolvedValue(false);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      expect(mockRefResolvesLocally).toHaveBeenCalledWith('/project', 'origin/main');
    });
    expect(mockRunGitWithTimeout).not.toHaveBeenCalled();
    expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent...');
  });

  it('threads a fetch-outcome observer into the CREATE-path ensureWorktree call, wired to the spawn warning', async () => {
    // The create path's fetch failure is invisible in ensureWorktree's RESULT
    // (verifiedStartPoint fallback still creates the tree), so the observer
    // is the only seam that can surface "created from a stale base".
    const { context, send } = makeContext();
    const task = makeTask();
    let capturedOptions: { onFetchOutcome?: (outcome: FetchIfStaleOutcome) => void } | undefined;
    mockEnsureWorktree.mockImplementation(async (...args: unknown[]) => {
      capturedOptions = args[2] as typeof capturedOptions;
      return { worktreePath: WORKTREE_PATH, branchName: 'reused-task-task-aaa', worktreeFolder: '7' };
    });

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    expect(typeof capturedOptions?.onFetchOutcome).toBe('function');
    capturedOptions!.onFetchOutcome!({ kind: 'failed', reason: 'network', message: 'fatal: Could not resolve host: github.com' });
    expect(send).toHaveBeenCalledWith(
      IPC.TASK_SPAWN_WARNING,
      task.id,
      expect.stringContaining('network unreachable'),
      undefined,
    );
  });

  it('does not probe when ensureWorktree actually created a worktree', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockEnsureWorktree.mockResolvedValue({
      worktreePath: WORKTREE_PATH,
      branchName: 'reused-task-task-aaa',
      worktreeFolder: '7',
    });

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');
    // Flush the microtask queue the probe would have scheduled on.
    await new Promise((resolve) => setTimeout(resolve, 0));

    expect(mockFetchIfStale).not.toHaveBeenCalled();
    expect(mockRunGitWithTimeout).not.toHaveBeenCalled();
  });

  it('does not probe for the other ensureWorktree null reasons (tree not alive on disk)', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    // ensureWorktree returned null but the worktree is a husk: the reuse gate
    // (which restates ensureWorktree's own condition) must not fire.
    mockIsInsideWorktree.mockReturnValue(false);

    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');
    await new Promise((resolve) => setTimeout(resolve, 0));

    expect(mockFetchIfStale).not.toHaveBeenCalled();
  });

  it('a note resolving in the reuse path\'s label-less window PENDS onto the next label push', async () => {
    // Red-green for the flaw a live preview caught: the reuse path emits no
    // label between the move and Phase 3's 'starting-agent', and the probe
    // (throttle-hit fetches especially) resolves inside that window. The old
    // no-entry no-op dropped the note there, so reuse drift never surfaced.
    const { context, window } = makeContext();
    const task = makeTask();
    revListReturns(2, 0);

    // NO label seeded: the map stays empty for the whole probe.
    await ensureTaskWorktree(context, task, stubTasksRepo, '/project');

    await vi.waitFor(() => {
      // Re-emitting the same phase is idempotent; polling this way covers the
      // final microtask between the rev-list resolving and the note landing.
      emitSpawnProgress(window, task.id, 'starting-agent');
      expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent... (base 2 behind)');
    });
  });

  it('a rev-list failure is swallowed - the spawn is never affected', async () => {
    const { context, window } = makeContext();
    const task = makeTask();
    emitSpawnProgress(window, task.id, 'starting-agent');
    mockRunGitWithTimeout.mockRejectedValue(new Error('git exploded'));

    await expect(ensureTaskWorktree(context, task, stubTasksRepo, '/project')).resolves.toBeUndefined();

    await vi.waitFor(() => {
      expect(mockRunGitWithTimeout).toHaveBeenCalled();
    });
    expect(getInFlightSpawnProgress()[task.id]).toBe('Starting agent...');
  });
});
